plugins/che-plugin-bayesian-lang-server/pom.xml, test/codeready-test-e2e/e2e-tests.sh, test/codeready-test-e2e/src/main/java/com/redhat/codeready/selenium/core/client/keycloak/cli/CodereadyKeycloakCliClient.java, test/codeready-test-e2e/src/main/java/com/redhat/codeready/selenium/core/client/keycloak/cli/CodereadyKeycloakCliCommandExecutor.java, test/codeready-test-e2e/src/test/resources/suites/CheOneThreadTestsSuite.xml
E2E tests report could be found [here](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/e2e-tests/job/daily-e2e-tests/49/E2E_20tests_20report/).
Upstream Che E2E test report could be found [here](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/e2e-tests/job/daily-e2e-tests/48/E2E_20tests_20report/).
=> Fix E2E tests to check CRW deployed by using operator

test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/VertxUserStoryTest.java
* Need to do minor corrections in the E2E test to increase reliability and reduce dependency when there are changes in the template project
* Related E2E test: _VertxUserStoryTest_
=> Test E2E: Correct the 'VertxUserStoryTest' to increase reliability

test/codeready-test-e2e/src/test/resources/suites/CheSuite.xml
* Modify the test suite _CheSuite_ according to the last changes
* Related issue: https://issues.jboss.org/browse/RACHEL-101
=> Test E2E: Modify the 'CheSuite' according to the last changes

test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/JavaEapUserStoryTest.java, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/JavaUserStoryTest.java
This PR:
- add info about https://issues.jboss.org/browse/CRW-37 known issue to **JavaUserStoryTest** and **JavaEapUserStoryTest** tests;
- not use ```quickExpandWithJavaScript()``` method for project opening in **JavaUserStoryTest** and **JavaEapUserStoryTest** tests
=> Selenium: add info about known issue, stabilize Java user story tests

plugins/che-plugin-bayesian-lang-server/src/main/java/org/eclipse/che/plugin/languageserver/bayesian/server/launcher/BayesianLanguageServerConfig.java
Tmp fix until https://github.com/eclipse/che/issues/12329 is fixed
Bayesian will be initialized for all .xml files, including pom
=> Fix initialization of Bayesian LS

README.adoc
Signed-off-by: Aurélien Pupier <apupier@redhat.com>
=> Fix typo in readme

test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/dashboard/workspaces/details/WorkspaceDetailsMachineActionsTest.java, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/languageserver/php/CodeReadyPhpFileEditingTest.java, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/NodeJsUserStoryTest.java, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/RedHatFuseUserStoryTest.java, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/WildFlyUserStoryTest.java
* Change timeout in the tests _NodeJsUserStoryTest_ and _WildFlyUserStoryTest_ to increase reliability 
* Add the 'try-catch' block to the test _RedHatFuseUserStoryTest_ according to the known issue (https://issues.jboss.org/browse/CRW-78)
* Change the value of the static field in the _WorkspaceDetailsMachineActionsTest_
* Add the _CodeReadyPhpFileEditingTest_ selenium test specified for CRW
=> Test E2E: Correct selenium tests

test/codeready-test-e2e/src/main/java/com/redhat/codeready/selenium/pageobject/dashboard/CodeReadyCreateWorkspaceHelper.java, test/codeready-test-e2e/src/main/java/com/redhat/codeready/selenium/pageobject/dashboard/CodereadyNewWorkspace.java, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/ClangCppUserStoryTest.java, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/DotNetUserStoryTest.java, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/GoUserStoryTest.java, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/JavaEapUserStoryTest.java, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/JavaUserStoryTest.java, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/NodeJsUserStoryTest.java, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/PhpUserStoryTest.java, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/PythonUserStoryTest.java, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/RedHatFuseUserStoryTest.java, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/SpringBootUserStoryTest.java, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/VertxUserStoryTest.java, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/WildFlyUserStoryTest.java, test/codeready-test-e2e/src/test/resources/crw-stage-images/cpp-stack.txt, test/codeready-test-e2e/src/test/resources/crw-stage-images/dotnet-stack.txt, test/codeready-test-e2e/src/test/resources/crw-stage-images/go-stack.txt, test/codeready-test-e2e/src/test/resources/crw-stage-images/java-rhel8-stack.txt, test/codeready-test-e2e/src/test/resources/crw-stage-images/java-stack.txt, test/codeready-test-e2e/src/test/resources/crw-stage-images/node-stack.txt, test/codeready-test-e2e/src/test/resources/crw-stage-images/php-stack.txt, test/codeready-test-e2e/src/test/resources/crw-stage-images/python-stack.txt
* Change the locators in the page object
* Create new class in pageobject.dashboard
* Add new folder to the resources
* Modify the selenium tests in the 'userstory' package  - workaround to run E2E tests against CRW installed from staging
=> Test E2E: Modify selenium tests from 'userstory' package

test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/dashboard/workspaces/details/WorkspaceDetailsMachineActionsTest.java, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/dashboard/workspaces/details/WorkspaceDetailsMachinesRamTest.java, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/git/AuthorizeOnGithubFromDashboardTest.java, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/git/AuthorizeOnGithubFromPreferencesTest.java, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/git/ImportWizardFormTest.java, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/miscellaneous/MachinesAsynchronousStartTest.java
* Replace the address of docker image related to the stage testing
* Add the timeout to the tests to increase reliability
=> Test E2E: Correct the selenium tests 

ide/codeready-ide-samples/src/main/resources/samples.json, ide/codeready-ide-stacks/src/main/resources/stacks.json
Change sample app location and modify commands
=> Change kitchensink sample

test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/editor/CodeReadySplitEditorFeatureTest.java, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/JavaEapUserStoryTest.java, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/JavaUserStoryTest.java, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/SpringBootUserStoryTest.java, test/codeready-test-e2e/src/test/resources/projects/Decorator.java
* Correct the selenium tests related to change the template application
* Clear up code in the selenium test
* Correct the file in the resources
* Related known issue: https://issues.jboss.org/browse/CRW-89
=> Test E2E: Correct the tests related to change the template application

test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/editor/CodeReadySplitEditorFeatureTest.java, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/JavaEapUserStoryTest.java, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/JavaUserStoryTest.java, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/RedHatFuseUserStoryTest.java, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/SpringBootUserStoryTest.java, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/VertxUserStoryTest.java, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/WildFlyUserStoryTest.java
=> Test E2: Add covering of the 'dependency analysis' command in selenium tests

test/codeready-test-e2e/pom.xml, test/codeready-test-e2e/src/main/java/com/redhat/codeready/selenium/core/executor/hotupdate/CodeReadyHotUpdateUtil.java, test/codeready-test-e2e/src/main/java/com/redhat/codeready/selenium/pageobject/account/CodeReadyKeycloakFederatedIdentitiesPage.java, test/codeready-test-e2e/src/main/java/com/redhat/codeready/selenium/pageobject/account/CodereadyKeycloakHeaderButtons.java, test/codeready-test-e2e/src/main/java/com/redhat/codeready/selenium/pageobject/dashboard/CodeReadyCreateWorkspaceHelper.java, test/codeready-test-e2e/src/main/java/com/redhat/codeready/selenium/pageobject/dashboard/CodereadyNewWorkspace.java, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/AbstractUserStoryTest.java, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/ClangCppUserStoryTest.java, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/DotNetUserStoryTest.java, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/GoUserStoryTest.java, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/JavaRhel8UserStoryTest.java, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/JavaUserStoryTest.java, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/NodeJsUserStoryTest.java, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/PhpUserStoryTest.java, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/PythonUserStoryTest.java, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/RedHatFuseUserStoryTest.java, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/SpringBootUserStoryTest.java, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/VertxUserStoryTest.java, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/WildFlyUserStoryTest.java, test/codeready-test-e2e/src/test/resources/suites/CodereadySuite.xml
This PR:
1. Extracts **AbstractUserStoryTest** which consists of createWorkspaceFromDashboard() test and setUo/tearDown methods.
1. Adds simple e2e test **JavaRhel8UserStoryTest** which ensure Java RHEL8 workspace started.
Test report can be found [here](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/CRW-1.0.0-GA-tests/job/6.17.x-daily-e2e-tests/15/E2E_20tests_20report/).
=>  Add e2e test JavaRhel8UserStoryTest

test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/dashboard/CreateAndDeleteProjectsTest.java
This PR updates CreateAndDeleteProjectsTest test according to changes in projects deleting on Dashboard.
=> Test E2E:  Update CreateAndDeleteProjectsTest test according to changes in upstream Che

test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/VertxUserStoryTest.java
* Add minor corrections to the selenium test _VertxUserStoryTest_ to increase reliability when launch it
=> Test E2E: Correct the selenium test 'VertxUserStoryTest'

test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/JavaUserStoryTest.java
* Delete the _try-catch_ block from selenium test _JavaUserStoryTest_ according to resolve the known issue CRW-123
* Add corrections to increase reliability when run it
=> Test E2E: Correct the selenium test 'JavaUserStoryTest'

test/codeready-test-e2e/src/main/java/com/redhat/codeready/selenium/pageobject/dashboard/CodeReadyCreateWorkspaceHelper.java
* Correct the _CodeReadyCreateWorkspaceHelper.java_ according to change the replacing address of docker image in the E2E _user-story_ tests
* Add the waiting of close _machine-edit-form_ to make the _user-story_ tests more reliability
=> Test E2E: Correct the 'CodeReadyCreateWorkspaceHelper' according to last changes

test/codeready-test-e2e/src/main/java/com/redhat/codeready/selenium/pageobject/dashboard/CodeReadyCreateWorkspaceHelper.java, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/NodeJsUserStoryTest.java
* Correct the _CodeReadyCreateWorkspaceHelper_ related to  change docker image address
* It allows to make success launch the e2e test _JavaRhel8UserStoryTest_
=> Test E2E:  Correct the 'CreateWorkspaceHelper' related to change image addres

test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/WildFlyUserStoryTest.java
* Add correction to the _WildFlyUserStoryTest_ to increase its reliability when run on CI
=> Test E2E: Correct the 'WildFlyUserStoryTest' to increase reliability

test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/GoUserStoryTest.java
* Add change to the selenium test _GoUserStoryTest_ according to update version of the go-stack
* Related new version of _go-stack_: _quay.io/crw/stacks-golang:1.1-1_
=> Test E2E:  Adapt the 'GoUserStoryTest' according to new version of stack

test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/JavaUserStoryTest.java, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/RedHatFuseUserStoryTest.java, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/SpringBootUserStoryTest.java, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/ThorntailUserStoryTest.java, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/VertxUserStoryTest.java
* Correct the E2E _userstory_ tests according to change in the output of the _dependency analysis_ command
* Correct the _ThorntailUserStoryTest_ according to change in the sample application
* Related known issue: https://issues.jboss.org/browse/CRW-253
=> Test E2E: Correct the 'userstory' tests according to the last changes

test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/PhpUserStoryTest.java
Add info about known https://issues.jboss.org/browse/CRW-237 issue to **PhpUserStoryTest** test.
=> [Selenium]: add info about known issue to PhpUserStoryTest test

test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/JavaUserStoryTest.java, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/SpringBootUserStoryTest.java
* Add the _'try-catch'_ block to the _JavaUserStoryTest_ related to registered new issue
* Correct _SpringBootUserStoryTest_ according to the last changes of sample application
=> Test E2E: Correct the 'userstory' tests according to the last changes 

test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/dashboard/StacksListTest.java, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/dashboard/workspaces/NewWorkspacePageTest.java, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/dashboard/workspaces/WorkspacesListTest.java, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/dashboard/workspaces/details/WorkspaceDetailsMachinesRamTest.java
This PR:
- correct expected stacks lists in **StacksListTest** test;
- correct expected stacks list on **NewWorkspaces** page;
- correct expected locator id on document page in **WorkspacesListTest** test;
- correct expected button state in **WorkspaceDetailsMachinesRamTest** test.
=> Test E2E: fix selenium tests from dashboard package

Jenkinsfile, pom.xml
=> Switch to Eclipse Che 6.19.4

test/codeready-test-e2e/README.adoc
Change-Id:...
CRW-324 s/oAuth/OAuth/g
Change-Id: I286617aecc0653cd54aa02e2c723c32b615e436d
=> CRW-324 s/oAuth/OAuth/g

test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/VertxUserStoryTest.java
This issue adapts **VertxUserStoryTest** selenium test according to changes in ```vertx-http-booster``` sample project.
=> [Selenium] Adapt VertxUserStoryTest selenium test according to project sample changes

dependencies/che-devfile-registry/devfiles/cakephp-ex/devfile.yaml, dependencies/che-devfile-registry/devfiles/cakephp-ex/meta.yaml
Signed-off-by: Victor Rubezhny <vrubezhny@redhat.com>
=> Add cakephp-ex devfiles

dependencies/che-devfile-registry/devfiles/php-web-simple/devfile.yaml, dependencies/che-devfile-registry/devfiles/php-web-simple/meta.yaml
Signed-off-by: Victor Rubezhny <vrubezhny@redhat.com>
=> Add php-web-simple devfiles

dependencies/che-devfile-registry/devfiles/spring-boot-http-booster/devfile.yaml, dependencies/che-devfile-registry/devfiles/spring-boot-http-booster/meta.yaml, dependencies/che-devfile-registry/devfiles/vertx-http-booster/devfile.yaml, dependencies/che-devfile-registry/devfiles/vertx-http-booster/meta.yaml
Signed-off-by: Thomas Mäder <tmader@redhat.com>
Added devfiles from spring-boot-http-booster and vertx
=> vertx and spring-boot examples

dependencies/che-plugin-registry/v3/plugins/redhat-developer/che-omnisharp-plugin/0.0.5/meta.yaml, dependencies/che-plugin-registry/v3/plugins/redhat-developer/che-omnisharp-plugin/latest/meta.yaml
Adds volume for nuget folder to save dependencies
=> Add volume for nuget folder for omnisharp plug-in

dependencies/che-devfile-registry/devfiles/php-web-simple/devfile.yaml
Adds simple debug configuration to run current script
=> Add debug configuration for php sample

dependencies/che-plugin-registry/build/dockerfiles/rhel.Dockerfile
Fixes https://issues.jboss.org/browse/CRW-473
Signed-off-by: Radim Hopp <rhopp@redhat.com>
=> Fixed problem with file premissions, when built in brew.

test/codeready-test-e2e/src/main/java/com/redhat/codeready/selenium/pageobject/account/CodereadyKeycloakHeaderButtons.java, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/dashboard/AccountTest.java, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/dashboard/workspaces/details/WorkspaceDetailsOverviewTest.java, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/git/AuthorizeOnGithubFromDashboardTest.java, test/codeready-test-e2e/src/test/resources/suites/CheOneThreadTestsSuite.xml, test/codeready-test-e2e/src/test/resources/suites/CheSuite.xml
This PR adapt next upstream selenium tests for CRW 2:
- **AccountTest**
- **WorkspaceDetailsOverviewTest**
- **AuthorizeOnGithubFromDashboard**
Selenium tests report - https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/CRW2-integration-tests-OCP/29/Selenium_20tests_20report/
=> [Selenium] Adapt upstream selenium tests for CRW

test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/dashboard/AccountTest.java, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/dashboard/workspaces/details/WorkspaceDetailsOverviewTest.java
Fix "```[ERROR] Non complying file: /mnt/hudson_workspace/workspace/Crw2-upstream-tests-pipeline/codeready-workspaces/test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/dashboard/AccountTest.java
[ERROR] Non complying file: /mnt/hudson_workspace/workspace/Crw2-upstream-tests-pipeline/codeready-workspaces/test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/dashboard/workspaces/details/WorkspaceDetailsOverviewTest.java```" error for selenium tests.
=> [Selenium] Format selenium tests

pom.xml
PR to demonstrate e2e problem in https://issues.redhat.com/browse/CRW-596
Change-Id: Iad5ddc1f8b8215613bd3273d65db8fefa28ef6aa
=> WIP DO NOT MERGE :: move up to Che 7.7.0

dependencies/che-plugin-registry/Jenkinsfile-single, dependencies/che-plugin-registry/v3/plugins/ms-python/python/2019.5.18875/meta.yaml
Fix VS code Python plugin, by correctly building its extension
=> Fix Python plugin

dependencies/che-devfile-registry/devfiles/03_camelk/devfile.yaml, dependencies/che-devfile-registry/devfiles/03_camelk/meta.yaml
CRW-609 initial devfile for camelk;
needs commands & verification that it runs against CRW2.1
Change-Id: I69225c2aea65e80b01f3acddb136cf78c21e1d76
=> WIP CRW-609 initial devfile for camelk; needs commands

dependencies/che-plugin-registry/v3/plugins/che-incubator/cpptools/0.1/meta.yaml, dependencies/che-plugin-registry/v3/plugins/che-incubator/typescript/1.35.1/meta.yaml, dependencies/che-plugin-registry/v3/plugins/eclipse/che-machine-exec-plugin/7.3.2/meta.yaml, dependencies/che-plugin-registry/v3/plugins/eclipse/che-machine-exec-plugin/7.3.3/meta.yaml, dependencies/che-plugin-registry/v3/plugins/eclipse/che-theia/7.3.2/meta.yaml, dependencies/che-plugin-registry/v3/plugins/eclipse/che-theia/7.3.3/meta.yaml, dependencies/che-plugin-registry/v3/plugins/ms-kubernetes-tools/vscode-kubernetes-tools/1.0.4/meta.yaml, dependencies/che-plugin-registry/v3/plugins/ms-python/python/2019.5.18875/meta.yaml, dependencies/che-plugin-registry/v3/plugins/ms-vscode/go/0.11.4/meta.yaml, dependencies/che-plugin-registry/v3/plugins/ms-vscode/node-debug2/1.33.0/meta.yaml, dependencies/che-plugin-registry/v3/plugins/redhat-developer/che-omnisharp-plugin/0.0.5/meta.yaml, dependencies/che-plugin-registry/v3/plugins/redhat/dependency-analytics/0.0.13/meta.yaml, dependencies/che-plugin-registry/v3/plugins/redhat/java/0.50.0/meta.yaml, dependencies/che-plugin-registry/v3/plugins/redhat/java8/0.50.0/meta.yaml, dependencies/che-plugin-registry/v3/plugins/redhat/php-debugger/1.13.0/meta.yaml, dependencies/che-plugin-registry/v3/plugins/redhat/php/1.0.13/meta.yaml, dependencies/che-plugin-registry/v3/plugins/redhat/vscode-apache-camel/0.0.18/meta.yaml, dependencies/che-plugin-registry/v3/plugins/redhat/vscode-apache-camel/0.0.22/meta.yaml, dependencies/che-plugin-registry/v3/plugins/redhat/vscode-openshift-connector/0.1.2/meta.yaml, dependencies/che-plugin-registry/v3/plugins/redhat/vscode-wsdl2rest/0.0.11/meta.yaml, dependencies/che-plugin-registry/v3/plugins/redhat/vscode-wsdl2rest/0.0.9/meta.yaml, dependencies/che-plugin-registry/v3/plugins/redhat/vscode-xml/0.9.1/meta.yaml, dependencies/che-plugin-registry/v3/plugins/redhat/vscode-yaml/0.4.0/meta.yaml, dependencies/che-plugin-registry/v3/plugins/sonarsource/sonarlint-vscode/0.0.2/meta.yaml
Change-Id:...
bump container refs to :2.1
Change-Id: Ie59854403da35bd08c0f1ebdeea8c43835313441
=> bump container refs to :2.1

dependencies/che-plugin-registry/v3/plugins/redhat/php/1.0.14/meta.yaml
Update plugin PHP intelephense 1.0.14 VSIX location
=> Update vscode-intelephense 1.0.14 plugin location

dependencies/che-plugin-registry/v3/plugins/redhat/java11/0.50.0/meta.yaml, dependencies/che-plugin-registry/v3/plugins/redhat/java11/0.55.1/meta.yaml, dependencies/che-plugin-registry/v3/plugins/redhat/java11/0.57.0/meta.yaml, dependencies/che-plugin-registry/v3/plugins/redhat/quarkus-java11/1.3.0a/meta.yaml
-  Adds a command to run endpoint into java11 plugins
-  Adds a volume for ~/.gradle folder into plugins where plugin-java11-rhel8:2.1 is used
=> Add gradle volume; Add command to run endpoint

dependencies/che-devfile-registry/devfiles/05_go/devfile.yaml
=> Fix workdir path for golang file. Fixes CRW-718

dependencies/che-devfile-registry/devfiles/03_spring-boot-http-booster/devfile.yaml, dependencies/che-devfile-registry/devfiles/03_vertx-http-booster/devfile.yaml, dependencies/che-devfile-registry/devfiles/05_go/devfile.yaml
Replaces '/' with '-' in endpoint's names in the devfile registry.
It is quick fix, the general fix should be done in https://github.com/eclipse/che/issues/16381.
https://issues.redhat.com/browse/CRW-717
cc @nickboldt
=> Replace '/' with '-' in endpoint's name

dependencies/che-devfile-registry/devfiles/03_java11-quarkus/devfile.yaml
based on the terminology used in https://quarkus.io/guides/getting-started#development-mode
https://issues.redhat.com/browse/CRW-701
=> rename commands to start Quarkus in dev mode

dependencies/che-devfile-registry/devfiles/03_java11-gradle/devfile.yaml, dependencies/che-devfile-registry/devfiles/03_java11-gradle/meta.yaml
-  Updates existing java-gradle devfile by replacing console-java-simple example with [gs-validating-form-input](https://github.com/crw-samples/gs-validating-form-input)
-  Updates list of commands:
https://issues.redhat.com/browse/CRW-412
cc @nickboldt @Ohrimenko1988
=> Update Gradle devfile to use new sample

test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/dashboard/CreateAndDeleteProjectsTest.java, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/dashboard/CreateWorkspaceTest.java, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/dashboard/workspaces/WorkspacesListTest.java, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/dashboard/workspaces/details/WorkspaceDetailsProjectsTest.java, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/workspaces/ProjectStateAfterRefreshTest.java, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/workspaces/ProjectStateAfterRenameWorkspaceTest.java, test/codeready-test-e2e/src/test/resources/suites/CheOneThreadTestsSuite.xml, test/codeready-test-e2e/src/test/resources/suites/CheSuite.xml
Update JavaMaven devfile sample name to ```vertx-health-checks-example-redhat```. Remove under repair tests from test suites.
=> [Selenium] Update JavaMaven devfile sample name

dependencies/che-devfile-registry/devfiles/05_go/devfile.yaml
Fixes problem with Go debugger
https://issues.redhat.com/browse/CRW-764
cc @nickboldt
=> Fix debugger in Go devfile

dependencies/che-devfile-registry/devfiles/03_java11-gradle/devfile.yaml
To avoid downloading extra dependencies in proxy mode we have to revert Gradle sample. 
https://issues.redhat.com/browse/CRW-739
=> Go back to old gradle sample

dependencies/che-devfile-registry/devfiles/05_cpp/devfile.yaml
Reverts redhat-developer/codeready-workspaces#277
=> Revert "[CRW 2.2] Update c++ devfile to use new sample"

dependencies/che-devfile-registry/devfiles/00_java-eap-maven/meta.yaml, dependencies/che-devfile-registry/devfiles/01_java-eap-thorntail/meta.yaml, dependencies/che-devfile-registry/devfiles/02_java-jboss-fuse/meta.yaml, dependencies/che-devfile-registry/devfiles/02_java-maven/meta.yaml, dependencies/che-devfile-registry/devfiles/03_camelk/meta.yaml, dependencies/che-devfile-registry/devfiles/03_java11-gradle/meta.yaml, dependencies/che-devfile-registry/devfiles/03_java11-quarkus/meta.yaml, dependencies/che-devfile-registry/devfiles/03_spring-boot-http-booster/meta.yaml, dependencies/che-devfile-registry/devfiles/03_vertx-http-booster/meta.yaml, dependencies/che-devfile-registry/devfiles/03_web-nodejs-simple/meta.yaml, dependencies/che-devfile-registry/devfiles/04_nodejs-configmap/meta.yaml, dependencies/che-devfile-registry/devfiles/04_nodejs-mongo/meta.yaml, dependencies/che-devfile-registry/devfiles/05_cpp/meta.yaml, dependencies/che-devfile-registry/devfiles/05_dotnet/meta.yaml, dependencies/che-devfile-registry/devfiles/05_go/meta.yaml, dependencies/che-devfile-registry/devfiles/05_php-cake/meta.yaml, dependencies/che-devfile-registry/devfiles/05_php-web-simple/meta.yaml, dependencies/che-devfile-registry/devfiles/05_python/meta.yaml
Updates the descriptions for devfiles by adding versions of frameworks and tools and adds missing tags.
https://issues.redhat.com/browse/CRW-521
=> [CRW 2.2] Update descriptions for devfiles

dependencies/che-devfile-registry/build/scripts/write_image_digests.sh, dependencies/che-plugin-registry/build/scripts/write_image_digests.sh
streamline error handling in write_image_digest
=> streamline error handling in write_image_digest

dependencies/che-devfile-registry/build/dockerfiles/rhel.Dockerfile, dependencies/che-devfile-registry/build/scripts/swap_images.sh, dependencies/che-plugin-registry/build/dockerfiles/rhel.Dockerfile, dependencies/che-plugin-registry/build/scripts/swap_images.sh
swap openjdk images for openj9 on p and z
=> swap openjdk images for openj9 on p and z

pom.xml
update crw 2.2 build to use che 7.14.1; disable tests (compilation failure)
Change-Id: I64fd7ee1fc06a5a767fd5545244ce6d35a1275b8
=> update crw 2.2 build to use che 7.14.1; disable tests (compilation failure)

dependencies/che-devfile-registry/devfiles/03_web-nodejs-simple/devfile.yaml, dependencies/che-devfile-registry/devfiles/04_nodejs-configmap/devfile.yaml, dependencies/che-devfile-registry/devfiles/04_nodejs-mongo/devfile.yaml, dependencies/che-devfile-registry/devfiles/05_python/devfile.yaml, dependencies/che-plugin-registry/v3/plugins/che-incubator/typescript/1.35.1/meta.yaml, dependencies/che-plugin-registry/v3/plugins/ms-python/python/2019.5.18875/meta.yaml, dependencies/che-plugin-registry/v3/plugins/ms-vscode/node-debug2/1.33.0/meta.yaml, dependencies/che-plugin-registry/v3/plugins/redhat/vscode-yaml/0.4.0/meta.yaml, dependencies/che-plugin-registry/v3/plugins/redhat/vscode-yaml/0.8.0/meta.yaml
CRW-919 switch to new shared sidecar for node/java/python
Change-Id: If5ce361eeca56aaf1f27e12b74dbf40125d62d24
=> CRW-919 switch to new shared sidecar for node/java/python

dependencies/che-devfile-registry/devfiles/04_nodejs-mongo/devfile.yaml
Fixes mongodb endpoint name
Related PR for the sample https://github.com/crw-samples/nodejs-mongodb-sample/pull/3
https://issues.redhat.com/browse/CRW-968
=> Change endpoint name in mongodb component

dependencies/che-devfile-registry/devfiles/00_java-eap-maven/devfile.yaml, dependencies/che-devfile-registry/devfiles/00_java-eap-maven/meta.yaml
Increase  memory limit for eap container
https://issues.redhat.com/browse/CRW-982
=> Add more memory for eap-maven

dependencies/che-plugin-registry/vsix.Jenkinsfile
Patches build of vscode-node debug
https://issues.redhat.com/browse/CRW-997
=> Patch build for vscode-node-debug

dependencies/che-devfile-registry/devfiles/02_java-maven/devfile.yaml
Fixes a problem with build commands in Java Maven stack
https://issues.redhat.com/browse/CRW-1005
=> Fix build for java-maven stack

test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/dashboard/AccountTest.java
Add **AccountTest** to UNDER_REPAIR group.
=> [Selenium ] Add AccountTest to UNDER_REPAIR group

dependencies/che-plugin-registry/vsix.Jenkinsfile, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/dashboard/AccountTest.java
Specifies commands to build `Jira and Bitbucket` extension https://bitbucket.org/atlassianlabs/atlascode/src/main/
It's possible to see the original list of command on the extension Deployments page https://bitbucket.org/atlassianlabs/atlascode/addon/pipelines/deployments#!/
It's necessary for PR https://github.com/eclipse/che-plugin-registry/pull/475
as a part of the issue https://github.com/eclipse/che/issues/16663
=> Specific commands to build Atlascode extension

dependencies/che-plugin-registry/vsix.Jenkinsfile
Uses a branch name as a current extension version. 
Fixup for the PR https://github.com/redhat-developer/codeready-workspaces/pull/316
=> Use branch name instead of fetching it with git command

dependencies/che-devfile-registry/devfiles/00_java-eap-maven/devfile.yaml, dependencies/che-devfile-registry/devfiles/03_java-microprofile/devfile.yaml, dependencies/che-devfile-registry/devfiles/03_java-microprofile/meta.yaml
Adds new devfile with microprofile sample from https://github.com/wildfly/quickstart/tree/20.0.0.Final
https://issues.redhat.com/browse/CRW-876
=> Add microprofile devfile

dependencies/che-devfile-registry/devfiles/03_camelk/meta.yaml
Replace **Apache Camel K** with  **Tooling for Apache Camel K**
https://issues.redhat.com/browse/CRW-1049
=> Fix name of Camel K devfile

dependencies/che-devfile-registry/devfiles/03_spring-boot-http-booster/devfile.yaml
Updates [spring-boot-http-booster ](https://github.com/snowdrop/rest-http-example) sample to use sb-2.3.x branch which provides version 4 of FMP.
https://issues.redhat.com/browse/CRW-452
=> Update sample for spring-boot-http-booster

dependencies/che-devfile-registry/build/scripts/write_image_digests.sh, dependencies/che-plugin-registry/build/scripts/write_image_digests.sh
update write_image_digests to handle openj9 special case
https://issues.redhat.com/browse/CRW-1193
=> fix for CRW-1193 -- update write_image_digests to handle openj9

dependencies/che-devfile-registry/build/scripts/write_image_digests.sh, dependencies/che-plugin-registry/build/scripts/write_image_digests.sh
remove all yaml files when disabling devfile
containers still showing up in index.json even though they were removed.
=> remove all yaml files when disabling devfile

dependencies/che-plugin-registry/vsix.Jenkinsfile
Adds cmake for building vscode-pythong
=> Install cmake for building vscode-python

dependencies/traefik/Jenkinsfile
Change-Id:...
tweaks for traefik
Change-Id: I790f6d45340ca2ab7333f9bab9b768df7c10e961
=> tweaks for traefik

test/codeready-test-e2e/src/main/java/com/redhat/codeready/selenium/core/executor/hotupdate/CodeReadyHotUpdateUtil.java, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/factory/CreateFactoryFromDevfileUrl.java, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/factory/DirectUrlFactoryWithKeepDirectoryTest.java, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/factory/DirectUrlFactoryWithRootFolderTest.java, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/factory/DirectUrlFactoryWithSpecificBranchTest.java, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/rolling/RollingUpdateStrategyWithStartedWorkspaceTest.java, test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/rolling/RollingUpdateStrategyWithWorkspacesStartStopTest.java, test/codeready-test-e2e/src/test/resources/suites/CheSuite.xml
Add factory and rolling update java selenium tests
https://issues.redhat.com/browse/CRW-131
=> [Selenium] Add factory and rolling update java selenium tests

dependencies/che-editor-intellij-community/devfiles/meta.yaml
Adding discoverable: false
Fixes https://github.com/eclipse/che/issues/18347
=> update meta.yaml to allow multiple workspaces

assembly/branding/product.json.template
Added configuration section with "cheCliTool" field in order to properly build a login command to Che Server in the User Dashboard.
depends on https://github.com/eclipse/che-dashboard/pull/107
https://github.com/eclipse/che/issues/13852
=> Added configuration section with "cheCliTool"

dependencies/che-devfile-registry/devfiles/03_web-nodejs-simple/meta.yaml, dependencies/che-devfile-registry/devfiles/04_nodejs-configmap/devfile.yaml, dependencies/che-devfile-registry/devfiles/04_nodejs-configmap/meta.yaml, dependencies/che-devfile-registry/devfiles/04_nodejs-mongo/meta.yaml
- Update info about node version 
- Fix nodejs-configmap sample
https://issues.redhat.com/browse/CRW-1412
=> Update info about node version; fix nodejs-configmap sample

dependencies/che-devfile-registry/devfiles/03_java11-quarkus/devfile.yaml
Set 0.0.0.0 as a host to run Quarkus app
https://issues.redhat.com/browse/CRW-1411
=> Set 0.0.0.0 as a host to run Quarkus app

product/util.groovy
* install skopeo >=1.1 from container if on rhel8; install from tarball if on rhel7; error if can't detect OS; detect skopeo version before attempting any installs
* don't reinstall podman if already present; don't install podman or docker if one is already installed; if neither, and not RHEL8, fail and call to action = install manually
Change-Id: I90c426331c2c1fb26b166ce6d4b1d5ea58cb614d
N/A
* https://issues.redhat.com/browse/CRW-1442 (overall)
* https://issues.redhat.com/browse/CRW-1443 (power)
* https://issues.redhat.com/browse/CRW-1444 (Z)
N/A
Reviewers, please comment how you tested the …
=> install skopeo >=1.1 from container if on RHEL8, try old way on RHEL7; don't attempt to install docker or podman on RHEL7

README.adoc
Cherry pick 122c7572 to branch crw-2.6-rhel-8
=> Fix README rendering

product/check-rpm-signatures.sh
Changes done as per https://issues.redhat.com/browse/CRW-1348?focusedCommentId=15754957&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15754957
=> Changes in check-rpm-signatures.sh to ensure it checks all images

product/util.groovy
add methods for:
runJob, getLastBuildId, waitForNewBuild, getLatestQuayImageAndTag, waitForNewQuayImage
Change-Id: I063f634ab2d92ffae5c22ac224b2e1dfe717b1ad
N/A
https://issues.redhat.com/browse/CRW-668
Required for https://gitlab.cee.redhat.com/codeready-workspaces/crw-jenkins/-/merge_requests/281
N/A
=> CRW-668 add methods for: runJob, getLastBuildId, waitForNewBuild, getLatestQuayImageAndTag, waitForNewQuayImage

dependencies/che-plugin-registry/v3/plugins/eclipse/che-theia/7.26.1/meta.yaml, dependencies/che-plugin-registry/v3/plugins/eclipse/che-theia/next/meta.yaml
Applies upstream patch https://github.com/eclipse/che-plugin-registry/pull/712 to CRW 2.7
https://issues.redhat.com/browse/CRW-1596
=> Declare a dedicated endpoint for exposing Che Theia mini-browser content

product/updateVersionAndRegistryTags.sh
Signed-off-by: Mykola Morhun <mmorhun@redhat.com>
Runs script to update plugin and devfile registries templates as was discussed [here](https://github.com/redhat-developer/codeready-workspaces/pull/429#issuecomment-782239426).
https://github.com/redhat-developer/codeready-workspaces/pull/429
N/A
N/A
=> Update plugin and devfile registries template

dependencies/che-devfile-registry/build/dockerfiles/Dockerfile, dependencies/che-plugin-registry/build/dockerfiles/Dockerfile, dependencies/che-plugin-registry/build/dockerfiles/rhel.install.sh
CRW-161o try workaround -- use s2i image so we don't have to install so much stuff into the ubi8 minimal builder image; increase retries and timeouts and parallel downloads; use deltarpm to speed up install process
Change-Id: I41bca4683e695fc8b31ea649885c3d82d64eaae1
N/A
N/A
=> CRW-1610 try workaround -- use s2i image + yum config settings

dependencies/che-plugin-registry/README.md
Signed-off-by: Aurélien Pupier <apupier@redhat.com>
=> fix typo depedencies -> dependencies

dependencies/che-plugin-registry/build.sh, dependencies/che-plugin-registry/build/dockerfiles/Dockerfile, dependencies/che-plugin-registry/build/scripts/keep_only_latest.sh
since we only include a single version of each plugin, might as well set LATEST_ONLY=true (remove the env var entirely; always call the script)
Change-Id: I94a1ee9a4ff207039c10ab3c12975bfbb9aedbaf
N/A
https://issues.redhat.com/browse/CRW-1614 -> https://issues.redhat.com/browse/RHDEVDOCS-2725
N/A
=> CRW-1614 remove --latest-only flag, set LATEST_ONLY = true

dependencies/che-editor-intellij-community/devfiles/workspace.yaml
Link "**che-editor-intellij-community**" devfile with _meta.yaml_ from **'crw-2-rhel-8**' branch.
=> Link "che-editor-intellij-community" devfile with 'crw-2-rhel-8'

dependencies/che-plugin-registry/v3/plugins/eclipse/che-theia/7.28.0/meta.yaml, dependencies/che-plugin-registry/v3/plugins/eclipse/che-theia/next/meta.yaml
Add machine-exec definition in che-theia
backport of https://github.com/eclipse/che/issues/19215
=> feat(che-theia): Add machine-exec definition in che-theia

dependencies/che-devfile-registry/devfiles/00_java-eap-maven/devfile.yaml
Avoids confusing prompt for a user
https://issues.redhat.com/browse/CRW-1707
https://github.com/eclipse/che/issues/19480
=> Mark jgroups endpoint as private in JBoss EAP maven devfile

dependencies/che-devfile-registry/devfiles/03_java-lombok/devfile.yaml, dependencies/che-devfile-registry/devfiles/03_java-lombok/meta.yaml, dependencies/che-devfile-registry/images/type-lombok.svg
Signed-off-by: Sun Seng David TAN <sutan@redhat.com>
Adding a new devfile with lombok
https://issues.redhat.com/browse/CRW-1420
Requires https://github.com/redhat-developer/codeready-workspaces-images/pull/21
Could be tested in prior versions with: https://github.com/redhat-developer/codeready-workspaces-images/pull/21#issue-586960352
=> feat(CRW-1420): Adding Java-Lombok devfile

.github/workflows/build-jobs.yaml, .github/workflows/image-build-pr-check.yaml, dependencies/che-plugin-registry/build.sh, dependencies/che-plugin-registry/build/dockerfiles/Dockerfile, dependencies/che-plugin-registry/build/dockerfiles/rhel.install.sh, dependencies/che-plugin-registry/che-editors.yaml, dependencies/che-plugin-registry/che-plugins.yaml, dependencies/che-plugin-registry/che-theia-plugins.yaml, dependencies/che-plugin-registry/tools/build/src/che-theia-plugin/che-theia-plugins-meta-yaml-generator.ts, dependencies/che-plugin-registry/tools/build/tests/che-theia-plugin/che-theia-plugins-meta-yaml-generator.spec.ts
* Sync with latest upstream to include --offline build fixes
* Add npm/yarn installation in rhel.install script
* Fixed Dockerfile so that it can be used in both here and Brew
* Renamed images to proper registry.redhat.io ones
This is prerequisite PR to changes that will be coming in codeready-workspaces-images.
Part of CRW-1648
=> Prepare for Brew builds

product/rhpkg-container-build.sh, product/rhpkg-container-build.sh_test_consoleText_fail3_brew-build-failed.txt, product/rhpkg-container-build.sh_test_consoleText_fail4_brew-build-unknown.txt, product/rhpkg-container-build.sh_test_consoleText_fail4_jenkins_error.txt, product/rhpkg-container-build.sh_test_consoleText_pass.txt
move nested bash into its own script so we can run it outside Jenkins
Requires an update to https://gitlab.cee.redhat.com/codeready-workspaces/crw-jenkins/-/blob/master/jobs/CRW_CI/get-sources-rhpkg-container-build_2.x.jenkinsfile to use this script
Change-Id: Ieabc0a1dc7dbfb936f41d16dd70e3dc7d2b89ff4
N/A
N/A
=> move nested bash into its own script so we can run it outside Jenkins

product/util.groovy
CRW-1799 add method installRedHatInternalCerts and run it when bootstrapping nodes (in case certs are not yet installed)
Change-Id: I98e119b8fe3ef204284897c9ebdceae05ea9c8a5
N/A
N/A
=> CRW-1799 add method installRedHatInternalCerts and run when bootstrapping

dependencies/che-plugin-registry/build/dockerfiles/Dockerfile, dependencies/che-plugin-registry/build/scripts/list_che_yaml.sh, dependencies/che-plugin-registry/build/scripts/list_referenced_images.sh, dependencies/che-plugin-registry/build/scripts/list_yaml.sh, dependencies/che-plugin-registry/build/scripts/swap_images.sh
* Copy che-*.yaml files into Dockerfile
* Fix list_referenced_images.sh to use new che-*.yaml files
* Fix swap_images.sh and list_yamls.sh to use new che-*.yaml files
Part of CRW-1824
=> Plugin registry script updates

dependencies/che-plugin-registry/build/dockerfiles/Dockerfile
Updates the base image. Needs to be merged before https://github.com/redhat-developer/codeready-workspaces-images/pull/35
Part of CRW-1831
=> Use ubi8 base in plugin registry Dockerfile

dependencies/che-plugin-registry/build/dockerfiles/rhel.install.sh
Remove yarn installation from the build Dockerfile as this isn't needed for Brew. Builds for this repo happen in GitHub action anyway so no big deal.
CRW-1833
=> Remove yarn installation step

dependencies/che-plugin-registry/che-theia-plugins.yaml
upgrade java extension to 0.75.0 and quarkus to v1.7.0
also adding the microprofile extension which is a requirement for quarkus extension
Quarkus: https://issues.redhat.com/browse/CRW-1697
Java: https://issues.redhat.com/browse/CRW-1699
upstream PR:
- Quarkus https://github.com/eclipse-che/che-plugin-registry/pull/650
- Java https://github.com/eclipse-che/che-plugin-registry/pull/890
=> feat(java): upgrade java extension to 0.75.0 and quarkus to v1.7.0

dependencies/che-plugin-registry/build/scripts/swap_plugins_memory.sh
Ignore shellcheck error to ensure correct `yq` execution
Fixes CRW-1904
=> fix(scripts): revert shellcheck suggestion to fix breakage

dependencies/che-plugin-registry/che-theia-plugins.yaml
=> fix(microprofile): fix repository url of vscode-microprofile

dependencies/che-plugin-registry/build/dockerfiles/Dockerfile, dependencies/che-plugin-registry/build/scripts/list_referenced_images.sh, dependencies/che-plugin-registry/build/scripts/list_yaml.sh
Includes devworkspaces files in digest generation logic
Fixes CRW-1947
=> fix(digests): include devworkspaces stuff in digest generation

product/util.groovy
according to https://www.jenkins.io/doc/book/pipeline/jenkinsfile/#string-interpolation we should use single quotes for secrets
Change-Id: I69bbce46bb95f9da8dc482c975e411bad65afd64
N/A
N/A
=> [2.10] use single quotes for secrets

dependencies/che-devfile-registry/build/dockerfiles/rhel.install.sh, dependencies/che-plugin-registry/build/dockerfiles/rhel.install.sh
Fix for CRW-2012:
* remove drpm (we really don't need it)
Also:
* remove jsonschema as it's no longer used in plugin and devfile registries;
* shellcheck fixes
Change-Id: Ibe975a2ad90d4572e84517884af7c9429d22534f
N/A
https://issues.redhat.com/browse/CRW-2012
N/A
=> chore: CRW-2012 remove drpm, dnf, and jsonschema installs

product/updateBaseImages.sh
Fix the cases when PR branch wouldn't be properly created in updateBaseImages.sh
N/A
N/A
=> fix: Fix updateBaseImages.sh PR branch creation

dependencies/che-devfile-registry/build/dockerfiles/Dockerfile, dependencies/che-plugin-registry/build/dockerfiles/Dockerfile
Updates httpd to deny access to security sensitive files such as .htaccess
Updates ssl to increase encryption strength
https://issues.redhat.com/browse/CRW-2118
N/A
=> fix: CRW-2118: Add httpd and ssl conf security updates 

dependencies/che-devfile-registry/devfiles/00_java11-maven-microprofile-bootable/devfile.yaml, dependencies/che-devfile-registry/devfiles/00_java11-maven-microprofile-bootable/meta.yaml, dependencies/che-devfile-registry/devfiles/00_java11-maven-microprofile-xp2/devfile.yaml, dependencies/che-devfile-registry/devfiles/00_java11-maven-microprofile-xp2/meta.yaml, dependencies/che-devfile-registry/devfiles/00_java8-maven-eap/devfile.yaml, dependencies/che-devfile-registry/devfiles/00_java8-maven-eap/meta.yaml
feat: CRW-1580 update to JBoss EAP 7.4 (with Maven 3.6 and newer branch/SHA for sample project); add TODO markers for the XP3 updates needed next week
Change-Id: I9e49baf4d74d75d5b03dfa070e2d53d8728dd5a5
N/A
N/A
=> feat: CRW-1580 update to JBoss EAP 7.4

product/buildAllInBrewCopyToQuay.sh, product/getLatestImageTags.sh, product/manifest/get-3rd-party-deps-manifests.sh, product/rhpkg-container-build.sh, product/tagRelease.sh
Signed-off-by: Flavius Lacatusu <flacatus@redhat.com>
Reff issue: https://issues.redhat.com/browse/CRW-2095
=> Add refference to codeready-workspaces-operator-bundle container

dependencies/job-config.json
feat: updating job-config.json to work with changes made in groovy fi…les for CRW-2149, adding more jobs.
=> Json updates for CRW-2149

product/manifest/get-3rd-party-deps-manifests.sh, product/manifest/get-3rd-party-deps-mvn.sh, product/manifest/get-3rd-party-deps-rpms.sh, product/manifest/get-3rd-party-deps-theia.sh, product/manifest/get-3rd-party-sources.sh
Add vsix plugins to theia manifest
Fix WORKSPACE variable init for local running
=> chore: add vsix plugins to theia manifests

product/ghira/ghira
chore: CRW-1684 - add affectsversion; link JIRA to GH and GH to JIRA with actual clickable URLs
Change-Id: Id77f172ef501ee3b795e74bc667224c905920fdc
N/A
N/A
=> chore: CRW-1684 - add affectsversion; link JIRA to GH and GH to JIRA with actual clickable URLs

dependencies/job-config.json
Updates che-plugin-generator version which is based on 7.36.x branch 
https://issues.redhat.com/browse/CRW-2360
=> chore: update che-plugin-generator version

dependencies/job-config.json
Updates che-plugin-generator version
https://issues.redhat.com/browse/CRW-2360
N/A
N/A
N/A
=> cheore: Update che-plugin-generator version

dependencies/che-plugin-registry/che-editors.yaml
Add IntelliJ IDEA editor meta configuration to CodeReady Workspaces.
Signed-off-by: Vladyslav Zhukovskyi <vzhukovs@redhat.com>
https://issues.redhat.com/browse/CRW-2276
Add IntelliJ IDEA editor meta configuration to CodeReady Workspaces
=> Add IDEA editor meta configuration

dependencies/che-plugin-registry/che-editors.yaml
Formats che-editors.yaml  
N/A
=> fix: format che-editors.yaml to fix a build

dependencies/che-plugin-registry/build/dockerfiles/Dockerfile
https://issues.redhat.com/browse/CRW-1883
=> fix: remove nobest form dockerfile

dependencies/che-plugin-registry/che-theia-plugins.yaml
Increases cpu limit for vscode-java sidecar
https://issues.redhat.com/browse/CRW-2453
N/A
N/A
=> feat: increase cpu limit for java sidecar

dependencies/job-config.json
Add async storage sidecar config to job-config.json
part of [CRW-1422](https://issues.redhat.com/browse/CRW-1422)
=> Add Async storage sidecar container to job-config

dependencies/che-devfile-registry/devfiles/04_python/meta.yaml
Adds a link to Python devfile version 2
https://issues.redhat.com/browse/CRW-2412
=> feat(devfile): Add link to the python devfile v2

dependencies/che-devfile-registry/devfiles/04_nodejs-simple/meta.yaml
Adds a link to devfile v2 in nodejs-simple sample
The link to the devfile: https://github.com/crw-samples/web-nodejs-sample/tree/devfilev2
https://issues.redhat.com/browse/CRW-2412
=> feat(devfile): Add link to the nodeJs-simple devfile v2

dependencies/che-devfile-registry/devfiles/02_java8-maven-fuse/meta.yaml
Introduces devfile version 2 for RH Fuse
Link to devfile: https://github.com/crw-samples/fuse-rest-http-booster/blob/devfilev2/devfile.yaml
=> feat(devfile): Introduce devfile version 2 for RH Fuse

dependencies/che-devfile-registry/devfiles/03_java8-maven-spring-boot-http-booster/meta.yaml
Introduces devfile version 2 for Java Spring Boot
Link to devfile: https://github.com/crw-samples/rest-http-example/blob/devfilev2/devfile.yaml
=> feat(devfile): Introduce devfile v2 for Java Spring Boot

dependencies/che-devfile-registry/devfiles/03_java11-maven-lombok/meta.yaml
Introduces devfile version 2 for Java Lombok
Link to devfile: https://github.com/crw-samples/lombok-project-sample/tree/devfilev2
=> feat(devfile): Add link to devfile v2 for java lombok

dependencies/che-devfile-registry/devfiles/03_java11-maven-vertx-http-booster/meta.yaml
Introduces devfile version 2 for Java Vertx-Booster
Link to devfile: https://github.com/crw-samples/vertx-http-example/blob/devfilev2/devfile.yaml
=> feat(devfile): Introduce devfile v2 for java-vertx-booster

dependencies/che-devfile-registry/devfiles/05_cpp/meta.yaml
Introduces devfile version 2 for CPP sample
Link to devfile: https://github.com/crw-samples/c-plus-plus/blob/devfilev2/devfile.yaml
=> feat(devfile): add link to cpp  devfile v2

dependencies/che-devfile-registry/devfiles/04_nodejs-mongo/meta.yaml
Migrate devfile to version 2 for nodejs-mongo sample
Link to devfile: https://github.com/crw-samples/nodejs-mongodb-sample/blob/devfilev2/devfile.yaml
=> feat(devfile): Add link to nodejs-mongo devfile v2

dependencies/che-devfile-registry/devfiles/05_php-cake/meta.yaml, dependencies/che-devfile-registry/devfiles/05_php-di/meta.yaml
Introduces devfile v2 for php based stacks.
PHP- CAKE:
PHP-DI:
Links to devfiles:
php-cake: https://github.com/crw-samples/cakephp-ex/blob/devfilev2/devfile.yaml
php-di: https://github.com/crw-samples/demo/tree/devfilev2
=> feat(devfile): add links to devfile v2 for php stacks

product/util2.groovy
=> feat: Add default webhook trigger config method to util2.groovy

dependencies/che-devfile-registry/devfiles/03_camelk/meta.yaml, dependencies/che-plugin-registry/che-theia-plugins.yaml
- Adds link to camel-k devfile version 2
- Change sidecar image for vscode-yaml plugin
link to the devfile: https://github.com/crw-samples/camel-k/blob/devfilev2/devfile.yaml
=> feat(devfile): Add link to camel-k devfile v2

dependencies/job-config.json, product/buildAllInBrewCopyToQuay.sh, product/containerExtract.sh, product/getCommitSHAForTag.sh, product/manifest/get-3rd-party-deps-manifests.sh, product/tagRelease.sh
=> feat: change references to plugins-* to udi

dependencies/che-devfile-registry/build/dockerfiles/test_entrypoint.sh, dependencies/che-devfile-registry/build/scripts/swap_images.sh, dependencies/che-devfile-registry/devfiles/00_java11-maven-microprofile-bootable/devfile.yaml, dependencies/che-devfile-registry/devfiles/02_java8-maven-fuse/devfile.yaml, dependencies/che-devfile-registry/devfiles/03_java11-maven-gradle/devfile.yaml, dependencies/che-devfile-registry/devfiles/03_java11-maven-lombok/devfile.yaml, dependencies/che-devfile-registry/devfiles/03_java11-maven-quarkus/devfile.yaml, dependencies/che-devfile-registry/devfiles/03_java11-maven-vertx-http-booster/devfile.yaml, dependencies/che-devfile-registry/devfiles/03_java11-maven-vertx/devfile.yaml, dependencies/che-devfile-registry/devfiles/03_java8-maven-spring-boot-http-booster/devfile.yaml, dependencies/che-devfile-registry/devfiles/04_nodejs-configmap/devfile.yaml, dependencies/che-devfile-registry/devfiles/04_nodejs-mongo/devfile.yaml, dependencies/che-devfile-registry/devfiles/04_nodejs-simple/devfile.yaml, dependencies/che-devfile-registry/devfiles/04_python/devfile.yaml, dependencies/che-plugin-registry/build/dockerfiles/test_entrypoint.sh, dependencies/che-plugin-registry/build/scripts/swap_images.sh, dependencies/che-plugin-registry/che-theia-plugins.yaml
feat: CRW-2463 CRW-2688 enable UDI sidecar images in registries
Change-Id: I6e633bcf8b67632901a57368e028aa59cb9f906f
N/A
N/A
=> feat: CRW-2463 CRW-2688 enable UDI sidecar images in registries

product/manifest/get-3rd-party-deps-theia.sh
In case we couldn't obtain CHE_THEIA_VERSION from CRW Theia Jenkins job log, we would try to fetch the branch version from BUILD_PARAMS file instead
https://issues.redhat.com/browse/CRW-2763
=> fix: fix manifest collection for Che Theia

.github/workflows/plugin-registry-build-publish-content.yaml, .github/workflows/plugin-registry-pr-check-build-publish-content.yaml, .github/workflows/plugin-registry-pr-check-build.yaml, README.adoc, dependencies/LATEST_IMAGES.sh, dependencies/che-devfile-registry/README.md, dependencies/che-devfile-registry/build.sh, dependencies/che-devfile-registry/build/dockerfiles/entrypoint.sh, dependencies/che-devfile-registry/build/scripts/update_template.sh, dependencies/che-plugin-registry/build.sh, dependencies/che-plugin-registry/build/dockerfiles/entrypoint.sh, dependencies/che-plugin-registry/che-theia-plugins.yaml, dependencies/che-plugin-registry/package.json, product/deleteQuayTags.sh, product/getLatestImageTags.sh, product/rhpkg-container-build.sh, product/tagRelease.sh, product/updateVersionAndRegistryTags.sh, product/util2.groovy
Change-Id:...
* chore: CRW-2818 con't: crw -> devspaces
* remove old code
Change-Id: Id280c9ceec9ddc37382fe4f540ff382edf3a10a4
N/A
N/A
=> chore: CRW-2818 con't: crw -> devspaces; remove old code

dependencies/che-plugin-registry/che-theia-plugins.yaml
chore: update js-debug from 1.52.2 to 1.66.0 #21250 CRW-2662
Change-Id: Ie769972e16e231f9dc3f4acaee6372dfb6e0fd51
N/A
N/A
=> Draft: chore: update js-debug from 1.52.2 to 1.66.0 (do not merge until upstream is merged)

dependencies/che-devfile-registry/build/scripts/generate_devworkspace_templates.sh, dependencies/che-devfile-registry/build/scripts/index.sh, dependencies/che-devfile-registry/versions.json
Reverts redhat-developer/devspaces#709
=> Revert "chore: add links.devWorkspaces field to the index.json"

dependencies/che-devfile-registry/build/dockerfiles/entrypoint.sh, dependencies/che-devfile-registry/build/dockerfiles/test_entrypoint.sh
Set INTERNAL_URL
https://issues.redhat.com/browse/CRW-2908
=> chore: update entrypoint.sh

product/installCatalogSourceFromIIB.sh, product/testLatestIIB.sh
Add scripts:
* `installCatalogSourceFromIIB.sh` : given an IIB image, install it in an OpenShift Cluster as a catalogsource and optionally install the DevSpaces Operator
* `testLatestIIB.sh` : automatically get the latest IIB for a given version of DevSpaces, and install a DevSpaces cluster in the current OpenShift cluster.
Usage examples:
1. Install CatalogSource for a specific IIB image in the `devspaces-testing` namespace, and install the `devspaces` operator from it
```bash
./installCatalogSourceFromIIB.sh \
--iib registry-proxy.engineering.redhat.com/rh-osbs/iib:225370 \
-n devspaces-testing \
--install-operator devspaces \
--channel stable
```
This script can be used to test any IIB image (e.g. DevWorkspace Operator)
2. Install DevSpaces cluster from the latest DS 3.0 IIB image in …
=> Add scripts to automate setting up IIB images for testing

product/filterIIBForDevSpaces.sh, product/installDevSpacesFromLatestIIB.sh
* 0aa95344 - Add script for extracting DS/DWO/WTO from IIB image amisevsk@redhat.com (20 hours ago)
* c97e30ad - refactoring and cleanup of requirements; add example and if no target indx image specified, default to quay.io/devspaces/iib:iibnum nboldt@redhat.com (20 seconds ago)
Change-Id: I6caa56b02a3ab8c51106928f6f3e752e9444d779
see details in https://github.com/redhat-developer/devspaces/pull/723
N/A
=> Add script for extracting DS/DWO/WTO from IIB image; some refactoring and cleanup

dependencies/che-devfile-registry/devfiles/02_java8-maven-fuse/meta.yaml
Update java version to 11 in the description of Java Fuse devfile
https://issues.redhat.com/browse/CRW-2591
=> chore: update java version in the description of fuse sample

product/installDevSpacesFromLatestIIB.sh
feat: support using local or curl'd dsc binary to perform install; provide option to delete before installing
feat: support using local or curl'd dsc binary to perform install; provide option to delete before installing
Change-Id: Ic087d4e7e4aab27de40921f91980eeda9bee31c8
Signed-off-by: Nick Boldt <nickboldt@gmail.com>
N/A
N/A
=> feat: support using local or curl'd dsc binary to perform install; provide option to delete before installing

dependencies/che-devfile-registry/build/dockerfiles/Dockerfile
=> chore: CRW-2985-cleanup Dockerfile

dependencies/che-devfile-registry/build/dockerfiles/Dockerfile, dependencies/che-devfile-registry/build/dockerfiles/rhel.cache_projects.sh, dependencies/che-devfile-registry/build/scripts/cache_projects.sh
=> chore: revert cache projects procedure

product/installCatalogSourceFromIIB.sh, product/installDevSpacesFromLatestIIB.sh
CRW-3129 initial code - add support for installing DWO as prestage before DS
Change-Id: I64b050ae33773f42999a135e8feaf95c1a268d7f
Signed-off-by: Nick Boldt <nickboldt@gmail.com>
N/A
N/A
=> CRW-3129  add support for installing DWO as prestage before DS

dependencies/che-devfile-registry/build/dockerfiles/Dockerfile
=> chore: add registry, organization, and tag args

dependencies/job-config.json
Signed-off-by: Roman Nikitenko <rnikiten@redhat.com>
Change target branch for code 3.1-rhel-8
https://issues.redhat.com/browse/CRW-2744
=> Change target branch for code 3.1-rhel-8

product/buildAllInBrewCopyToQuay.sh, product/getLatestImageTags.sh, product/manifest/get-3rd-party-deps-manifests.sh, product/tagRelease.sh
Signed-off-by: Roman Nikitenko <rnikiten@redhat.com>
Add devspaces-code to scripts
https://issues.redhat.com/browse/CRW-2744
=> Add devspaces-code to scripts

dependencies/che-plugin-registry/che-editors.yaml
Add VSCode editor meta configuration to Devspaces.
How I tested it:
1. Build plugin registry to get resulted image
2. Retag the image and push it into docker registry
3. Setup instance with Devspaces
4. Update CheCluster CustomResourceDefinition to use my image
5. Started a workspace by using factory https://github.com/devspaces-samples/python-hello-world?che-editor=che-incubator/che-code/insiders
https://issues.redhat.com/browse/CRW-2288
=> feat: add code editor

dependencies/job-config.json
Change-Id:...
disable theia jobs
Change-Id: Ia937e4e43f6f76f21dc89d7a166c86e6a064a6db
N/A
N/A
=> disable theia jobs

dependencies/che-plugin-registry/che-theia-plugins.yaml
Use newer version of VSCode Python extension
[CRW-2619](https://issues.redhat.com/browse/CRW-2619)
=> chore: Update Python extension to newer version

dependencies/che-devfile-registry/build.sh, dependencies/che-devfile-registry/build/scripts/generate_devworkspace_templates.sh, dependencies/che-devfile-registry/build/scripts/index.sh, dependencies/che-devfile-registry/versions.json
Generates devworkspaces (devworkspace-che-theia-latest.yaml) with Code editor for each sample from the devfile registry. 
As a result each sample folder should contain 3 files:
```
devworkspace-che-code-insiders.yaml  devworkspace-che-theia-latest.yaml  meta.yaml
```
Each sample in **index.json** looks like:
```json
{
"displayName": "Go",
"description": "Stack with Go",
"tags": [
"Tech-Preview",
"Go",
"Golang",
"UBI8"
],
"icon": "/images/type-go.svg",
"links": {
"v2": "https://github.com/devspaces-samples/golang-health-check/tree/devspaces-3-rhel-8",
"devWorkspaces": {
"eclipse/che-theia/latest": "/devfiles/05_go/devworkspace-che-theia-latest.yaml",
"che-incubator/che-code/insiders": …
```
=> chore: generate DevWorksapces with Code editor

dependencies/job-config.json
Update 3.x and 3.2 source branches to v2.8.1 for Traefik
https://issues.redhat.com/browse/CRW-3136
=> Update 3.x and 3.2 source branches to v2.8.1 for Traefik

dependencies/job-config.json
=> Enabling 3.2 jobs by default

product/updateVersionAndRegistryTags.sh
=> Fix addition of nulls to job-config.json

dependencies/che-devfile-registry/build/scripts/generate_devworkspace_templates.sh
Remove **-g** parameter form the npm install command
=> chore: install che-theia and che-code devworkspace libs locally

dependencies/che-devfile-registry/devfiles/05_dotnet/meta.yaml, dependencies/che-plugin-registry/che-theia-plugins.yaml
Remove the .NET stack and related plugins
https://issues.redhat.com/browse/CRW-3288
=> chore: remove dotnet stack and related plugins

dependencies/che-devfile-registry/devfiles/04_nodejs-mongo/meta.yaml, dependencies/che-devfile-registry/devfiles/04_nodejs-simple/meta.yaml, dependencies/che-devfile-registry/devfiles/05_cpp/meta.yaml
spelling fix of meta.yaml files containing mentions of 'Node.js'
https://issues.redhat.com/browse/RHDEVDOCS-4300
=> rhdevdocs-4300 spelling fix

dependencies/che-plugin-registry/build/dockerfiles/Dockerfile, dependencies/che-plugin-registry/build/dockerfiles/entrypoint.sh, dependencies/che-plugin-registry/build/dockerfiles/postgresql.Dockerfile
- Install postgresql via rpms
- Use ubi-httpd as a be image
https://issues.redhat.com/browse/CRW-3295
=> chore: fix build; use rpms to install postgresql

dependencies/job-config.json
Sets [Che-Code `7.54.x`](https://github.com/che-incubator/che-code/tree/7.54.x) as the base for DevSpaces 3.3.
As Che-Code is integrated into the overall Che release process.
=> Update Che-Code branch for DevSpaces 3.3

dependencies/che-plugin-registry/build.sh, dependencies/che-plugin-registry/build/dockerfiles/Dockerfile, dependencies/che-plugin-registry/build/dockerfiles/ovsx-installer.Dockerfile
Trying to fix the problem with Node for ppc/z arches
https://issues.redhat.com/browse/CRW-3295
=> chore: install node instead of using from tarball

.github/workflows/plugin-registry-build.yaml, .github/workflows/plugin-registry-pr-check-build-publish-content.yaml, .github/workflows/plugin-registry-pr-check-build.yaml, .github/workflows/plugin-registry-pr-check-shellcheck.yaml, dependencies/che-plugin-registry/build.sh
=> chore: improve GH actions

dependencies/che-devfile-registry/devfiles/00_java11-maven-eap/meta.yaml, dependencies/che-devfile-registry/devfiles/00_java11-maven-microprofile-xp3/meta.yaml
[CRW-3447](https://issues.redhat.com/browse/CRW-3447) remove the EAP and EAP XP3 microprofile samples
Change-Id: Id38997450fad827b26ac7f176b7db45c228f7c4f
N/A
N/A
=> CRW-3447 remove the EAP 7.4 and EAP XP3 microprofile samples

dependencies/job-config.json
I just want to change this one name to better fit how it will be used in devspaces-operators container.yaml
=> CRW-3138 proposed change to an operator dependency name.

dependencies/che-devfile-registry/devfiles/05_dotnet/meta.yaml
feat: CRW-2456 reintroduce dotnet sample for dotnet 7; supporting x/Z/P arches
Change-Id: I3b3b7f784c2ac72f6bc9193d74ab2cd9fa42b2c6
N/A
https://issues.redhat.com/browse/CRW-2456
N/A
=> feat: CRW-2456 reintroduce dotnet sample for dotnet 7; supporting x/Z/P arches

product/installCatalogSourceFromIIB.sh
Use alternate catalogSouce name when --install-operator is not specified in order to allow using script without installing an operator.
There's a lot of extra line changes due to trimming trailing whitespace automatically -- sorry.
N/A
N/A
=> Make --install-operator parameter optional in `installCatalogSourceFromIIB.sh`

product/manifest/get-3rd-party-sources.sh, product/tagRelease.sh
=> Change crw-build to devspaces-build to fix scripts

product/tagRelease.sh, product/updatePNCBuildConfigs.sh
- tagRelease.sh should be invoking updatePNCBuildConfigs.sh script, as one will be almost always used with each other.
- minor formatting fix for updatePNCBuildConfigs.sh
https://issues.redhat.com/browse/CRW-3879
=> feat: Integrate PNC script into tagRelease.sh

product/tagRelease.sh
Do not skip tagging latest, if latest existing tag is the same as the one being supplied to the script (tagging should be skipped if CSV_VERSION is strictly "less than" LATEST_TAG, not "less than or equal")
and use check=silent to reduce possible output
https://issues.redhat.com/browse/CRW-3805
=> fix: fix DS samples latest tagging condition

dependencies/che-plugin-registry/che-editors.yaml
chore: fix: CRW-4074 add duplicate entry for che-incubator/che-code/insiders
question: should the attributes.version also be insiders, or keep it latest?
N/A
https://issues.redhat.com/browse/CRW-4074
N/A
=> chore: fix: CRW-4074 add duplicate entry for che-incubator/che-code/insiders

product/containerExtract.sh, product/installDevSpacesFromLatestIIB.sh
Minor fixups to issues I encountered trying to use `installDevSpacesFromLatestIIB.sh` to test Dev Spaces pre-release.
PR may be bad/wrong in ways I don't understand, I kind of just did the simplest thing to make it work for me.
https://issues.redhat.com/browse/CRW-4083
=> Fix installDevSpacesFromLatestIIB.sh for Brew IIBs

dependencies/che-plugin-registry/openvsx-sync.json
fix: CRW-4111 hardcode the known good versions of python and jupyter plugins (from 3.4 release)
Change-Id: I794b5d4c86e3c294033ec63825808393c1d2f4ea
N/A
https://issues.redhat.com/browse/CRW-4111
Build new plugin reg container and operator-bundle
Deploy to airgapped cluster
Verify that python sample can be loaded and that all recommended plugins ([python](https://open-vsx.org/extension/ms-python/python) can be installed
=> fix: CRW-4111 hardcode the known good versions of python and jupyter plugins (from 3.4 release)

dependencies/che-devfile-registry/README.md, dependencies/che-devfile-registry/build.sh, dependencies/che-devfile-registry/build/dockerfiles/test_entrypoint.sh, dependencies/che-devfile-registry/build/scripts/generate_devworkspace_templates.sh, dependencies/che-devfile-registry/build/scripts/index.sh
Don't generate devworkspaces with che-theia editor
https://issues.redhat.com/browse/CRW-4134
=> chore: remove dw+theia generation

product/checkImagesInCSV.sh
fix: CRW-4077 prevent checkImagesInCSV.sh from choking on unexpected yaml
Change-Id: I1de41f767828ad3712477f8a5f2abea5bec8b817
N/A
https://issues.redhat.com/browse/CRW-4077
N/A
=> fix: CRW-4077 prevent checkImagesInCSV.sh from choking on unexpected yaml

product/copyVSIXToStage.sh
Add script for copying plugin files and sources to spmm-util.
Used in the jenkins job but can also be run locally.
https://issues.redhat.com/browse/CRW-4049
=> CRW-4049 Add copy script

product/buildCatalog.sh, product/checkImagesInCSV.sh, product/checkImagesInIIB.sh, product/copyIIBsToQuay.sh, product/filterIIB.sh, product/getLatestImageTags.sh, product/installCatalogSourceFromIIB.sh, product/installDevSpacesFromLatestIIB.sh
fix: update to OPM 4.12 and OSE container 4.12 (CRW-4192, OCPBUGS-11841)
Change-Id: Ie591948a8145d6f9b9e3154ab0dc7bc4334b06b6
N/A
https://issues.redhat.com/browse/CRW-4192
https://issues.redhat.com/browse/OCPBUGS-11841
N/A
=> fix: chore: update to OPM 4.12 and OSE container 4.12 (CRW-4192, OCPBUGS-11841)

dependencies/job-config.json
It aligns Dev Spaces 3.6.0 to recent version of Dev Spaces 3.5.0-0.1679521107.p, and 3.7.0 to 3.6.0.
https://issues.redhat.com/browse/CRW-4324
=> Set "CSV_VERSION_PREV": "3.5.0-0.1679521107.p"

dependencies/che-plugin-registry/openvsx-sync.json
chore: CRW-4307 instead of pulling pre-release versions, use 1.17.0 (seems like a bug in the openvsx scraper... but won't matter when we move to building vsix files inside RH and just consuming them
Change-Id: I0d3acc4c816d5b8dcee185f3ea26c0176bab1b78
N/A
N/A
=> chore: CRW-4307 instead of pulling pre-release versions, use 1.17.0 

dependencies/che-plugin-registry/openvsx-sync.json
fix: update python and jupyter to latest stable releases 2023.6.1 / 2023.3.100 (CRW-433, CRW-4111)
Change-Id: I077a8f6b83557fd8cc3aeeb853e0034d91b4d63c
N/A
https://issues.redhat.com/browse/CRW-4334
See https://issues.redhat.com/browse/CRW-4334?focusedId=22185682&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-22185682
=> fix: update python and jupyter to latest stable releases 2023.6.1 / 2023.3.100 (CRW-433, CRW-4111)

dependencies/che-devfile-registry/versions.json
Bump version of devworkspace generator tool to pick up changes made by https://github.com/eclipse-che/che-devfile-registry/pull/755
https://github.com/eclipse/che/issues/22155
N/A
N/A
N/A
=> chore: update version of devworkspace generator tool

dependencies/job-config.json
Update previous release to 3.7
https://issues.redhat.com/browse/SPMM-13405
=> SPMM-13405 Update previous release to 3.7

dependencies/che-devfile-registry/build/dockerfiles/Dockerfile, dependencies/che-devfile-registry/build/dockerfiles/rhel.install.sh, dependencies/che-plugin-registry/build/dockerfiles/Dockerfile, dependencies/che-plugin-registry/build/dockerfiles/openvsx-builder.Dockerfile, dependencies/che-plugin-registry/build/dockerfiles/ovsx-installer.Dockerfile, dependencies/che-plugin-registry/build/dockerfiles/rhel.install.sh
chore: CRW-4585 update to python 3.11, pip latest, nodejs18, ubi 8.8
Change-Id: Idcc1a49b195430481db20ef9526ba2ad3f7b60e4
N/A
N/A
=> chore: CRW-4585 update to python 3.11, pip latest, nodejs18, ubi 8.8

product/uploadAssetsToGHRelease.sh
Add a line to specifically find and remove the associated tag and maybe fix dsc.
=> Update uploadAssetsToGHRelease.sh to delete tags

dependencies/che-plugin-registry/build/scripts/download_vsix.sh, dependencies/che-plugin-registry/openvsx-sync.json
- Use versions instead of allVersions to find latest compatible extensions
- Fix extensions' names
https://issues.redhat.com/browse/CRW-4593
N/A
=> feat: use versions to find the latest greatest extension

dependencies/che-plugin-registry/build/dockerfiles/ovsx-installer.Dockerfile
Updates ovsx to 0.8.3
https://issues.redhat.com/browse/CRW-4585
N/A
N/A
=> chore: update ovsx to 0.8.3

product/rhpkg-container-build.sh
chore: CRW-4821 if no get-sources.sh found, just run `brew container-build`
Change-Id: I4c71e4db18c97098052038fad827729f1a8dc40f
N/A
N/A
=> chore: CRW-4821 if no get-sources.sh found, just run brew container-build

dependencies/job-config.json
I think just updating the CSV here is all thats needed?
=> Update job-config.json for 3.9.1

product/rhpkg-container-build.sh
https://issues.redhat.com/browse/CRW-4976
@nickboldt 
If this change looks good I can add something similar to the remaining get-sources.sh files.
Will also, obviously, have to make corresponding changes to the get-sources-rhpkg job in jenkins
=> Fix: CRW-4976 add handling for different downstream branches.

dependencies/job-config.json
=> Update previous csv to 3.9.1, update 3.10 to latest tag.

dependencies/che-plugin-registry/build/dockerfiles/Dockerfile, dependencies/che-plugin-registry/build/dockerfiles/openvsx-builder.Dockerfile, dependencies/che-plugin-registry/build/dockerfiles/ovsx-installer.Dockerfile
Changed upstream, now to change midstream.
https://github.com/eclipse-che/che-plugin-registry/pull/1835
=> Update Plugin Registry source images, mostly for CVE fixes.

dependencies/che-devfile-registry/devfiles/java11-maven-lombok__lombok-project-sample/meta.yaml, dependencies/che-devfile-registry/devfiles/java11-maven-quarkus__quarkus-quickstarts/meta.yaml
UDI provides a few java versions. Let's update a description for java based samples to make them more general
DEPENDS ON:
- https://github.com/redhat-developer/devspaces-images/pull/531
- https://github.com/devspaces-samples/lombok-project-sample/pull/10
https://issues.redhat.com/browse/CRW-4948
=> chore: update description of java based samples

dependencies/che-devfile-registry/devfiles-extra/02_java11-maven-fuse/meta.yaml
The devfile is unmaintained and still based on old versions of Fuse. Fuse will be reaching EOL anyway soon.
New devfiles based on Red hat build of Camel would better to be added (later and if some time to do it is allocated for that)
=> Remove Camel devfile

dependencies/che-plugin-registry/che-editors.yaml
Updates che-idea editor definition to use https protocol in endpoints
https://issues.redhat.com/browse/CRW-5380
N/A
N/A
=> use https protocol in  idea editor's endpoints

dependencies/che-plugin-registry/che-editors.yaml
Updates che-idea editor definition to use https protocol in endpoints
https://issues.redhat.com/browse/CRW-5380
N/A
N/A
N/A
=> fix: use https endpoints for idea editor

dependencies/che-plugin-registry/openvsx-sync.json
Adds next extensions into the embedded plugin registry:
Indent one space - https://open-vsx.trilogy.devspaces.com/extension/usernamehw/indent-one-space
Markdown PDF - https://open-vsx.org/extension/yzane/markdown-pdf
markdownlint - https://open-vsx.org/extension/DavidAnson/vscode-markdownlint
Robot Framework Language Server - https://open-vsx.org/extension/robocorp/robotframework-lsp
Trailing Spaces - https://open-vsx.org/extension/shardulm94/trailing-spaces
vscode-base64 - https://open-vsx.org/extension/adamhartford/vscode-base64
https://issues.redhat.com/browse/CRW-5445
N/A
N/A
=> chore: add more extensions into embedded plugin registry

content-set-check/ubi8-brew/content_sets_pulp.repo, dependencies/che-devfile-registry/build/dockerfiles/content_sets_rhel8.repo, dependencies/che-plugin-registry/README.md, dependencies/che-plugin-registry/build/dockerfiles/content_sets_rhel8.repo, product/buildAllInBrewCopyToQuay.sh, product/buildInBrewCopyToQuay.sh, product/getCommitSHAForTag.sh, product/getLatestImageTags.sh, product/getLatestRPM.sh, product/manifest/get-3rd-party-deps-manifests.sh, product/manifest/get-3rd-party-deps-rpms.sh, product/query-pulp.sh, product/util2.groovy
Some of the scripts that we use frequently but rarely update still had http when there are now https urls available.
https://issues.redhat.com/browse/CRW-5708
=> CRW-5708 Updating leftover instances of http to https.

dependencies/che-plugin-registry/che-editors.yaml
- Adds Tech-Preview tag for idea editor
- set schemaVersion 2.2.2 in editors' definitions
index.json:
https://issues.redhat.com/browse/CRW-6039
=> Add Tech-Preview tag for idea editor

dependencies/job-config.json
https://issues.redhat.com/browse/CRW-5765
=> Update traefik to 2.10.7

.devfile.yaml
Update main devfile: 
- bump schema version to 2.2.2
- set https endpoint
N/A
=> Update main devfile; bump schema version; set https endpoint

product/getCVEAffectedRPMs.sh
feat: CRW-2382 new tool to collect affected RPMs/base images for a list of containers in Errata
Change-Id: I6d28ddf479225509fb17d151c44cf9e474f3d39d
N/A
N/A
=> feat: CRW-2382 new tool to collect affected RPMs/base images for a list of containers in Errata

.devfile.yaml
=> Add postStart command to workaround problem with podman

dependencies/job-config.json
https://issues.redhat.com/browse/CRW-6308
=> Update Traefik to v3.0.0

product/copyIIBsToQuay.sh
https://issues.redhat.com/browse/CRW-6537
=> Fix copyIIBsToQuay script to always use job-config.json from devspaces-3-rhel-8

dependencies/che-devfile-registry/devfiles/TP__dotnet__dotnet-web-simple/meta.yaml
Use .NET 8 in the description of .NET sample
https://issues.redhat.com/browse/CRW-6827
=> update .net sample description with .NET 8.0

dependencies/che-plugin-registry/build/dockerfiles/rhel.Dockerfile
Container is still B grade after rebuild, adding a dnf update should fetch any missing fixes.
=> Update rhel.Dockerfile to include dnf update

dependencies/job-config.json
=> Update 3.16 branch job-config.json for 3.16.1

dependencies/job-config.json
=> Update main job-config.json for 3.16.1

dependencies/che-plugin-registry/openvsx-sync.json
Adds `cnshenj.vscode-task-manager` and `Kelvin.vscode-sshfs` into the embedded plugin registry
https://issues.redhat.com/browse/CRW-7481
https://issues.redhat.com/browse/CRW-7482
Add [cnshenj.vscode-task-manager](https://open-vsx.org/extension/cnshenj/vscode-task-manager) and [Kelvin.vscode-sshfs](https://open-vsx.org/extension/Kelvin/vscode-sshfs) extensions into the embedded plugin registry
=> chore: add vscode-task-manager and vscode-sshfs extensions

dependencies/job-config.json
https://issues.redhat.com/browse/CRW-8326
=> Updating job-config and CSV version prev for 3.20 branch.
