ide/codeready-ide-stacks/src/main/resources/stacks.json

Please add the tests needed. I don't understand what is the policy as the stack is more or less duplicated in 3 repositories (<Eclipse Che, RH Che and this one) with different sets of tests.

Activate Camel Language Server for Red hat Fuse stack #64

---

test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/JavaEapUserStoryTest.java
test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/JavaUserStoryTest.java
test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/RedHatFuseUserStoryTest.java

This PR:
- add checking ```Apache Camel``` language server initialization in ```Red Hat Fuse``` stack;
- remove info about known https://issues.jboss.org/browse/CRW-37 issue from **JavaUserStoryTest** and **JavaEapUserStoryTest** tests.

Selenium: remove info about known issue, check Apache Camel ls initialization

---

test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/debugger/CodeReadyStepIntoStepOverStepReturnWithChangeVariableTest.java
test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/editor/CodeReadySplitEditorFeatureTest.java
test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/editor/autocomplete/CodeReadyAutocompleteProposalJavaDocTest.java
test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/intelligencecommand/CodeReadyAutocompleteCommandsEditorTest.java
test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/intelligencecommand/CodeReadyCheckIntelligenceCommandFromToolbarTest.java

* Add the missed annotations _@Override_ to the selenium tests

Tets E2E: Add the missed annotations '@Override' to selenium tests

---

ide/codeready-ide-stacks/pom.xml
ide/codeready-ide-stacks/src/main/resources/stacks.json
pom.xml

This PR:
* introduces nightly profile to codeready-workspaces assembly. The profile makes Che server use images from quay.io which will be updated daily (or nightly)
* sets images in stacks.json to be coming from RHCC (they do not exist yet)
```
mvn clean install -Pnightly
```
It is also possible to set property on the command line:
```
mvn clean install -Dnightly=true
```
The profile is declared in the root pom, so if you want to build `ide/codeready-ide-stacks` module individually, make sure you set a property, rather than use a profile.

Introduce nightly profile

---

ide/codeready-ide-stacks/src/main/resources/stacks.json

1.0.0 does not exist in quay.io
I have created such a tag to unblock everyone.

Fix tag for RHEL8 image

---

assembly/assembly-dashboard-war/pom.xml
assembly/assembly-ide-war/pom.xml
assembly/assembly-wsagent-server/pom.xml
assembly/assembly-wsagent-war/pom.xml
assembly/assembly-wsmaster-war/pom.xml
assembly/codeready-ide-gwt-app/pom.xml
assembly/codeready-workspaces-assembly-main/pom.xml
assembly/pom.xml
ide/codeready-ide-samples/pom.xml
ide/codeready-ide-stacks/pom.xml
ide/codeready-product-info/pom.xml
ide/pom.xml
plugins/che-plugin-bayesian-lang-server/pom.xml
plugins/ls-bayesian-agent/pom.xml
plugins/pom.xml
pom.xml
test/codeready-test-e2e/pom.xml
test/codeready-test-performance/pom.xml
test/pom.xml

Eclipse Che 6.17.0 has being released.
This request moves master branch to next version which is compatible with Eclipse Che 6.18.0-SNAPSHOT

Move to 6.18.0-SNAPSHOT

---

test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/DotNetUserStoryTest.java
test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/JavaEapUserStoryTest.java
test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/JavaUserStoryTest.java

* Change the timeout in the selenium tests to increase reliability when run on CI
* Related selenium tests:  _DotNetUserStoryTest_, _JavaEapUserStoryTest_, _JavaUserStoryTest_
* Depends on the https://github.com/eclipse/che/pull/12402

Test E2E: Change timeout in the selenium tests

---

test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/dashboard/workspaces/AddOrImportProjectFormTest.java

It fixes on address **kitchensink-example** in E2E tests:
```
https://github.com/openshift-quickstart/kitchensink-example.git
>
https://github.com/che-samples/kitchensink-example.git
```
Test report could be find [here](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/CRW-1.0.0-GA-tests/job/6.17.x-daily-e2e-tests/12/E2E_20tests_20report/).
Related issue: https://issues.jboss.org/browse/CRW-89

Fix e2e tests to use new address of kitchensink

---

test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/editor/CodeReadySplitEditorFeatureTest.java
test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/miscellaneous/CodeReadyFindTextFeatureTest.java
test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/miscellaneous/CodeReadyResolveDependencyAfterRecreateProjectTest.java
test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/JavaUserStoryTest.java
test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/RedHatFuseUserStoryTest.java
test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/VertxUserStoryTest.java
test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/workspaces/CodeReadyCreateWorkspaceOnDashboardTest.java
test/codeready-test-e2e/src/test/resources/projects/Decorator.java
test/codeready-test-e2e/src/test/resources/suites/CheSuite.xml

It is version of another PR https://github.com/redhat-developer/codeready-workspaces/pull/93 made by @artaleks9 without redundant commits.
It includes:
* Correct the tests related to change the template application
* Correct the tests to provide success execution
Test results could be found [here|https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/pre-release-user-stories-e2e-tests-against-OCP/6/].

Correct the e2e tests due to changed the kitchensink application

---

test/codeready-test-performance/README.adoc
test/codeready-test-performance/pom.xml
test/codeready-test-performance/src/test/jmeter/codeready-test-scenario-with-building-project.jmx
test/codeready-test-performance/src/test/jmeter/codeready-test-scenario-with-opening-file.jmx
test/codeready-test-performance/src/test/jmeter/codeready-test-scenario.jmx

* Extend performance Jmeter scenario actions that emulate a adding maven project into a workspace, build and validate building for each virtual user
* Extend performance Jmeter scenario actions that emulate a adding maven project into a workspace,and opening a file
* Add maven parameter for select a scenario which should be launched.
* Change description and add info with descritions od scenarios
**Depended issue:**  https://issues.jboss.org/browse/CRW-144
**Note:** all scenarios have been checked on the rial cluster: `https://console.iokhrime-ocp.crew`
@Ohrimenko1988 @rhopp @dmytro-ndp - rview pls.

Add extended performance scenarios

---

test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/JavaEapUserStoryTest.java
test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/JavaUserStoryTest.java
test/codeready-test-e2e/src/test/resources/suites/CodereadyOneThreadTestsSuite.xml
test/codeready-test-e2e/src/test/resources/suites/CodereadySuite.xml

There are flaky e2e user story tests of class JavaEapUserStoryTest, which are failing with blank pages. For example:
https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/CRW-pre-release-tests/job/pre-release-user-stories-e2e-tests-against-OCP/20/E2E_20tests_20report/
It happens with inherited tests which have more one test method and 
when they are performed in a test suite or in a package (if you'll launch as a single test it is not reproduced).
This PR describes test methods inside the **JavaEapUserStoryTest** class explicitly, rather then inherit it from **JavaUserStoryTest** implicitly. 
Resulted test report could be found [here](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/CRW-pre-release-tests/job/pre-release-user-stories-e2e-tests-ag …

 Fix blank screenshots in e2e tests result report

---

test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/debugger/CodeReadyPhpProjectDebuggingTest.java
test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/debugger/CodeReadyStepIntoStepOverStepReturnWithChangeVariableTest.java
test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/editor/CodeReadySplitEditorFeatureTest.java
test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/editor/autocomplete/CodeReadyAutocompleteProposalJavaDocTest.java
test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/intelligencecommand/CodeReadyAutocompleteCommandsEditorTest.java
test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/intelligencecommand/CodeReadyCheckIntelligenceCommandFromToolbarTest.java
test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/intelligencecommand/CodeReadyCommandsPaletteTest.java
test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/intelligencecommand/CodeReadyMacrosCommandsEditorTest.java
test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/languageserver/CodeReadyGolangFileEditingTest.java
test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/languageserver/CodeReadyJsonFileEditingTest.java
test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/miscellaneous/CodeReadyWorkingWithSplitPanelTest.java
test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/DotNetUserStoryTest.java

* Set the test methods of e2e tests explicitly related the known issue (https://issues.jboss.org/browse/CRW-155)
* Correct the 'user-story' e2e test to increase reliability

Test E2E: Fix blank screenshots in e2e tests result report

---

test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/dashboard/CreateAndDeleteProjectsTest.java
test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/dashboard/StacksListTest.java
test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/dashboard/workspaces/NewWorkspacePageTest.java
test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/dashboard/workspaces/WorkspacesListTest.java
test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/dashboard/workspaces/details/WorkspaceDetailsMachineActionsTest.java

This PR:
- increase timeout for checking that Maven plugin status bar is closed(```CreateAndDeleteProjectsTest```);
- update expected stack description for **Java 1.8** stack(```StacksListTest```);
- update expected stacks list on **New Workspaces** page(```NewWorkspacePageTest```);
- fix expected page title on **Codeready** document web page(```WorkspacesListTest```);
- fix machine name generation(not use ```_``` symbol) in ```WorkspaceDetailsMachineActionsTest```.

Selenium: fix selenium tests from dashboard package

---

test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/JavaUserStoryTest.java
test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/RedHatFuseUserStoryTest.java
test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/SpringBootUserStoryTest.java

* Add corrections to the selenium tests _user-story_  to adapt for CRW deployed to OCP 4.0
* Related known issue: https://issues.jboss.org/browse/CRW-148

Test E2E: Adapt the 'user-story' e2e tests to CRW deployed to OCP 4.0

---

assembly/assembly-dashboard-war/src/main/webapp/assets/branding/product.json.template
ide/codeready-product-info/src/main/resources/com/redhat/codeready/plugin/product/info/client/CodeReadyLocalizationConstant.properties

This PR fixes outdated links in CRW to product page of "Codeready Workspaces for Openshift": https://access.redhat.com/products/red-hat-codeready-workspaces-for-openshift/

Get rid of 'for-openshift' in docs and help path

---

test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/dashboard/CreateAndDeleteProjectsTest.java

This PR increases timeout for checking that ```MavenPlugin``` status bar is closed in **CreateAndDeleteProjectsTest**.

Selenium: fix unstable CreateAndDeleteProjectsTest selenium test

---

test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/JavaUserStoryTest.java
test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/NodeJsUserStoryTest.java

* Correct the _JavaUserStoryTest_ to make independent from changes of CVE recommended versions when checking the error marker of Bayesian language server
* Related e2e tests: _JavaUserStoryTest_, _JBossEapUserStoryTest_

Test E2E: Correct the 'JavaUserStoryTest' to increase reliability

---

Jenkinsfile

Its' workaround suggested by @eivantsov to fix the build of Eclipse Che 6.19.3:
```
[INFO] Che Workspace Loader :: Web App .................... FAILURE [ 30.267 s]
...
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (build-workspace-loader) on project che-workspace-loader: An Ant BuildException has occured: exec returned: 2
[ERROR] around Ant part ...<exec failonerror="true" dir="/mnt/hudson_workspace/workspace/crw_stable-branch/che/workspace-loader" executable="npm">... @ 7:122 in /mnt/hudson_workspace/workspace/crw_stable-branch/che/workspace-loader/target/antrun/build-main.xml
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (build-workspace-loader) …
```

Fix build of Eclipse Che 6.19.3

---

test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/Node10UserStoryTest.java

Fixup of regression in e2e user stories tests: blank pages in https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/pre-release/view/OCP%203.11/job/pre-release-user-stories-e2e-tests-against-OCP/114/E2E_20tests_20report/failsafe-report.html#com.redhat.codeready.selenium.userstory.Node10UserStoryTest 

Fix Node10UserStoryTest.java

---

test/codeready-test-e2e/src/main/java/com/redhat/codeready/selenium/pageobject/dashboard/CodereadyNewWorkspace.java

* Correct the 'id selector' in the _CodereadyNewWorkspace_ related to the last change on dashboard
* Related e2e test:  _JavaRhel8UserStoryTest_

Test E2E: Correct the 'id selector' related to last change on the dashboard

---

test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/ClangCppUserStoryTest.java
test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/SpringBootUserStoryTest.java
test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/userstory/ThorntailUserStoryTest.java

* Change the expected proposal text of the autocomplete container in the _ClangCppUserStoryTest_
* Change the command to expand the project tree in the _SpringBootUserStoryTest_
* Change the wait timeout of closing maven plugin info panel in the _ThorntailUserStoryTest_

Test E2E: Correct the 'userstory' tests to increase reliability

---

test/codeready-test-e2e/src/main/java/com/redhat/codeready/selenium/pageobject/CodereadyOpenShiftLoginPage.java
test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/ocpoauth/LoginExistedUserWithOpenShiftOAuthTest.java
test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/ocpoauth/LoginNewUserWithOpenShiftOAuthTest.java

This PR adds methods to ```CodereadyOpenShiftLoginPage``` pageobject for selection identity provider from providers list on ```Log in with...``` page and add info about known https://issues.jboss.org/browse/CRW-202 issue to selenium tests from ```ocpoauth``` package.

[Selenium] Select identity provider from providers list

---

test/codeready-test-e2e/src/main/java/com/redhat/codeready/selenium/core/CodereadySeleniumSuiteModule.java
test/codeready-test-e2e/src/main/java/com/redhat/codeready/selenium/pageobject/site/CodereadyLoginPage.java
test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/ocpoauth/LoginExistedUserWithOpenShiftOAuthTest.java
test/codeready-test-e2e/src/test/java/com/redhat/codeready/selenium/ocpoauth/LoginNewUserWithOpenShiftOAuthTest.java

This PR fixes locator of *Openshift v4* button on login page in E2E java selenium tests:
It is related to https://issues.jboss.org/browse/CRW-327 and is required for https://issues.jboss.org/browse/CRW-202.

Fix locator of OpenShift OAuth link button in e2e tests

---

ide/codeready-ide-samples/src/main/resources/samples.json

Should fix https://issues.jboss.org/browse/CRW-368
Signed-off-by: Radim Hopp <rhopp@redhat.com>

Add `npm install` into `web-nodejs-simple` sample run command.

---

ide/codeready-ide-samples/src/main/resources/samples.json
ide/codeready-ide-stacks/src/main/resources/stacks.json

Renaming stack to .NET Core 2.1 for consistency with the actual version of the `registry.redhat.io/codeready-workspaces/stacks-dotnet-rhel8` image used.  See supporting documentation, attribute `DOTNET_CORE_VERSION=2.1` [1].  As an aside, version 2.0 was deprecated in October 2018 [2].
[1]
https://access.redhat.com/containers/?tab=tech-details#/registry.access.redhat.com/codeready-workspaces/stacks-dotnet-rhel8
[2]
https://dotnet.microsoft.com/platform/support/policy/dotnet-core

Update metadata to .NET 2.1 to reflect version used

---

dependencies/che-devfile-registry/devfiles/cpp/devfile.yaml
dependencies/che-devfile-registry/devfiles/cpp/meta.yaml
dependencies/che-devfile-registry/devfiles/go/devfile.yaml
dependencies/che-devfile-registry/devfiles/go/meta.yaml
dependencies/che-devfile-registry/devfiles/java-jboss-fuse/devfile.yaml
dependencies/che-devfile-registry/devfiles/java-jboss-fuse/meta.yaml
dependencies/che-devfile-registry/devfiles/python/devfile.yaml
dependencies/che-devfile-registry/devfiles/python/meta.yaml

Signed-off-by: Anatoliy Bazko <abazko@redhat.com>

Add go, cpp, python devfiles

---

dependencies/che-devfile-registry/devfiles/nodejs-mongo/devfile.yaml
dependencies/che-devfile-registry/devfiles/nodejs-mongo/meta.yaml

This PR adds the nodejs mongo devfile.
All images have been replaced from upstream to use ones from registry.redhat.io.
Currently, the sample this devfile uses lives in a fork of the upstream sample. This fork is needed because the sample includes kubernetes yaml files needed for deploying the application that hardcodes image names. The fork changes the images to be images from the red hat registry.
In order for this devfile to be merged (and WIP removed) we need to have this modified sample be in a better location.
Tested on che.openshift.io.
Signed-off-by: Josh Pinkney <joshpinkney@gmail.com>

WIP - Added nodejs mongo devfile

---

dependencies/che-devfile-registry/devfiles/dotnet/devfile.yaml
dependencies/che-devfile-registry/devfiles/dotnet/meta.yaml
dependencies/che-devfile-registry/devfiles/java-eap-maven/devfile.yaml
dependencies/che-devfile-registry/devfiles/java-eap-maven/meta.yaml
dependencies/che-devfile-registry/devfiles/java-eap-thorntail/devfile.yaml
dependencies/che-devfile-registry/devfiles/java-eap-thorntail/meta.yaml
dependencies/che-devfile-registry/devfiles/java-maven/devfile.yaml
dependencies/che-devfile-registry/devfiles/java-maven/meta.yaml

Adds several devfiles:
-  dotnet with [dotnet-web-simple](https://github.com/che-samples/dotnet-web-simple) application
-  java-maven with [console-java-simple](https://github.com/che-samples/console-java-simple.git) application
-  java-eap-maven with [kitchensink-example](https://github.com/che-samples/kitchensink-example.git)
- java-eap-thorntail with [rest-http-redhat](https://github.com/thorntail-examples/rest-http-redhat) application

Add dotnet, java maven and jboss devfiles

---

dependencies/che-devfile-registry/devfiles/web-nodejs-simple/devfile.yaml
dependencies/che-devfile-registry/devfiles/web-nodejs-simple/meta.yaml

This PR brings in the web-nodejs-simple devfile.
This devfile differs from the devfile in the che-devfile-registry in 2 ways:
- Uses registry.redhat.io/codeready-workspaces/stacks-node-rhel8 which includes node 10
- nodemon isn't available in the current version of the image so it has replaced all references of nodemon with node (though I believe @nickboldt is working on this so that this image has nodemon)
Signed-off-by: Josh Pinkney <joshpinkney@gmail.com>

 web-nodejs-simple devfile

---

entrypoint.sh

Same change happened in upstream in commit https://github.com/eclipse/che/commit/79c6ec0703fb5c00458e2fa00b4df9f586c0c5a9#diff-1da4013f60e1b92b5613cf9680423a88
Without this change, latest codeready server fails with 
```
Using embedded assembly...
cp: cannot stat '/home/jboss/codeready/templates/*': No such file or directory
```
Signed-off-by: Radim Hopp <rhopp@redhat.com>

Remove samples.json logic.

---

dependencies/che-plugin-registry/v3/plugins/redhat/dependency-analytics/0.0.13/meta.yaml

Sets `quay.io/crw/stacks-java-rhel8:2.0` image for dependency-analytics plugin

Change image for dependency-analytics

---

dependencies/che-plugin-registry/build/dockerfiles/entrypoint.sh

Make entrypoint script respect environment variables 
```
CHE_THEIA_OVERRIDE
THEIA_RUNTIME_OVERRIDE
MACHINE_EXEC_OVERRIDE
```
in order to allow overriding images used for theia and machine exec plugin at runtime.

Add ability to override Theia, Theia runtime, and Machine Exec images

---

dependencies/che-plugin-registry/v3/plugins/che-incubator/cpptools/0.1/meta.yaml
dependencies/che-plugin-registry/v3/plugins/che-incubator/typescript/1.35.1/meta.yaml
dependencies/che-plugin-registry/v3/plugins/ms-python/python/2019.5.18875/meta.yaml
dependencies/che-plugin-registry/v3/plugins/ms-vscode/go/0.11.4/meta.yaml
dependencies/che-plugin-registry/v3/plugins/ms-vscode/node-debug2/1.33.0/meta.yaml
dependencies/che-plugin-registry/v3/plugins/redhat-developer/che-omnisharp-plugin/0.0.5/meta.yaml
dependencies/che-plugin-registry/v3/plugins/redhat/dependency-analytics/0.0.13/meta.yaml
dependencies/che-plugin-registry/v3/plugins/redhat/java/0.50.0/meta.yaml
dependencies/che-plugin-registry/v3/plugins/redhat/java8/0.50.0/meta.yaml
dependencies/che-plugin-registry/v3/plugins/redhat/php-debugger/1.13.0/meta.yaml
dependencies/che-plugin-registry/v3/plugins/redhat/php/1.0.13/meta.yaml
dependencies/che-plugin-registry/v3/plugins/redhat/vscode-apache-camel/0.0.18/meta.yaml
dependencies/che-plugin-registry/v3/plugins/redhat/vscode-wsdl2rest/0.0.9/meta.yaml
dependencies/che-plugin-registry/v3/plugins/redhat/vscode-xml/0.9.1/meta.yaml
dependencies/che-plugin-registry/v3/plugins/redhat/vscode-yaml/0.4.0/meta.yaml

https://issues.jboss.org/browse/CRW-493
Change plugin meta.yaml#spec#containers#container#args(it is Dockerfile#CMD) to start remote plugin endpoint binary.  
Notice:
We don't touch meta.yaml#spec#containers#container#command (it is Dockerfile#ENTRYPOINT), so entrypoint.sh scripts defined in the Dockerfile#ENTRYPOINT should work fine.
Signed-off-by: Oleksandr Andriienko <oandriie@redhat.com>

Fix launching remote plugins according to use latest che-plugin-broker.

---

Jenkinsfile
patches/0001-Provision-proxy-settings-on-init-containers.patch

Apply patch derived from https://github.com/eclipse/che/pull/15264 to Che during build to workaround https://github.com/eclipse/che/issues/15265 ([CRW-494](https://issues.jboss.org/browse/CRW-494))
I can't test this change directly.
If merged, this PR makes https://github.com/redhat-developer/codeready-workspaces/pull/201/ obsolete.

Apply patch to fix proxy issue from upstream Che during build

---

dependencies/che-devfile-registry/devfiles/00_java-eap-maven/devfile.yaml
dependencies/che-devfile-registry/devfiles/01_java-eap-thorntail/devfile.yaml
dependencies/che-devfile-registry/devfiles/02_java-maven/devfile.yaml

It is unnecessary to have `MAVEN_CONFIG` for `registry.redhat.io/codeready-workspaces/stacks-java-rhel8:2.0`.  In some cases it could be erroneously to have `MAVEN_CONFIG`, for example, if user  uses `mvnw`.
For more information take a look at https://github.com/eclipse/che/issues/13926 and https://github.com/eclipse/che-devfile-registry/pull/160

Remove MAVEN_CONFIG env from maven based containers

---

dependencies/che-plugin-registry/v3/plugins/redhat/quarkus-java11/1.2.0/meta.yaml

Adds args into quarkus plug-in: 
```yaml
args:
- sh
- -c
- ${PLUGIN_REMOTE_ENDPOINT_EXECUTABLE}
```
cc @nickboldt

Add args into quarkus plugin

---

dependencies/che-devfile-registry/Jenkinsfile
dependencies/che-devfile-registry/build/dockerfiles/Dockerfile
dependencies/che-devfile-registry/build/dockerfiles/entrypoint.sh
dependencies/che-devfile-registry/build/dockerfiles/rhel.Dockerfile
dependencies/che-devfile-registry/build/dockerfiles/rhel.cache_projects.sh
dependencies/che-devfile-registry/build/dockerfiles/rhel.entrypoint.sh
dependencies/che-devfile-registry/build/dockerfiles/rhel.install.sh
dependencies/che-devfile-registry/build/scripts/cache_images.sh
dependencies/che-devfile-registry/build/scripts/cache_projects.sh
dependencies/che-devfile-registry/build/scripts/index.sh
dependencies/che-devfile-registry/build/scripts/write_image_digests.sh

Update the Jenkins script for [syncing the devfile registry to pkgs.devel](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/CRW_CI/view/Releng/job/crw-devfileregistry_sync-github-to-pkgs.devel-pipeline/). 
- Use `rhel.Dockerfile` copied directly from upstream repo and apply *all* required patches in CI (hence the monstrous `sed` sequence).
- Add building of new source `devfiles.tgz`, which ends up in the lookaside.
I've tested the changes as best I can locally.
Sample patched dockerfile (output of running the big `sed` on `rhel.Dockerfile`):
```dockerfile
#
#
#
#
FROM ubi8-minimal:8.1-398 as builder
USER 0
################# 
################# 
ARG BOOTSTRAP=false
ENV BOOTSTRAP=${BOOTSTRAP}
ARG USE_DIGESTS=true
ENV USE_DIGESTS=${USE_DIGESTS}
COPY root-local.tgz …
```

CRW-590: enable offline devfiles registry build

---

dependencies/che-devfile-registry/devfiles/00_java-eap-maven/meta.yaml
dependencies/che-devfile-registry/devfiles/01_java-eap-thorntail/meta.yaml
dependencies/che-devfile-registry/devfiles/02_java-jboss-fuse/meta.yaml
dependencies/che-devfile-registry/devfiles/02_java-maven/meta.yaml
dependencies/che-devfile-registry/devfiles/03_camelk/meta.yaml
dependencies/che-devfile-registry/devfiles/03_java11-gradle/meta.yaml
dependencies/che-devfile-registry/devfiles/03_java11-quarkus/meta.yaml
dependencies/che-devfile-registry/devfiles/03_spring-boot-http-booster/meta.yaml
dependencies/che-devfile-registry/devfiles/03_vertx-http-booster/meta.yaml
dependencies/che-devfile-registry/devfiles/03_web-nodejs-simple/meta.yaml
dependencies/che-devfile-registry/devfiles/04_nodejs-mongo/meta.yaml
dependencies/che-devfile-registry/devfiles/05_cpp/meta.yaml
dependencies/che-devfile-registry/devfiles/05_dotnet/meta.yaml
dependencies/che-devfile-registry/devfiles/05_go/meta.yaml
dependencies/che-devfile-registry/devfiles/05_php-cake/meta.yaml
dependencies/che-devfile-registry/devfiles/05_php-web-simple/meta.yaml
dependencies/che-devfile-registry/devfiles/05_python/meta.yaml

With upstream version 7.8.0, we should be able to use the icons stored in the registry itself, to avoid having to cache icons during build.

Use relative image paths in devfile meta.yamls

---

dependencies/che-devfile-registry/build/dockerfiles/entrypoint.sh

The CRW registries are provisioned with services devfile-registry and plugin-registry; this breaks the fallback airgap option for attempting to determine a local URL
Note that this fallback option is pretty untested and should not be relied upon in general; it could break in many circumstances, e.g. across namespace boundaries, depending on cluster configuration.
The change is only made for the devfile registry at the moment, since it's less likely to cause issues.

Fix entrypoint for devfile registry, since crw service has different name

---

Jenkinsfile
assembly/codeready-workspaces-assembly-dashboard-war/pom.xml

Update replaceregexp to use 'che-service.factory.ts' instead of 'che-branding.ts'.
https://issues.redhat.com/browse/CRW-673
The build result after:
Signed-off-by: Oleksii Orel <oorel@redhat.com>

CRW-673 update replaceregexp to use 'che-service.factory.ts'

---

dependencies/che-devfile-registry/devfiles/05_dotnet/devfile.yaml

Changes endpoint's name from `5000/tcp` to `hello-endpoint`. 
Looks like the problem is because the name contains `/` symbol. 
The real problem should be fixed in upstream
https://issues.redhat.com/browse/CRW-717
cc @nickboldt

Change endpoint's name

---

dependencies/che-devfile-registry/devfiles/03_nodejs-configmap/devfile.yaml
dependencies/che-devfile-registry/devfiles/03_nodejs-configmap/meta.yaml

This PR introduces a new nodejs configmap devfile based off of https://github.com/nodeshift-starters/nodejs-configmap.
(I assume registry.redhat.io/codeready-workspaces/stacks-node-rhel8:2.1 will be released with codeready workspaces but I was testing against registry.redhat.io/codeready-workspaces/stacks-node-rhel8:2.0-5.1580285284)

Add nodejs configmap sample

---

dependencies/che-devfile-registry/devfiles/00_java-eap-maven/devfile.yaml

Updates  **build and run in debug** command in **java-eap-maven** devfile to make debugger possible to attache to the remote process and debug eap application.
https://issues.redhat.com/browse/CRW-724
cc @nickboldt

Update the command to debug kitchensink-eap application

---

assembly/codeready-workspaces-assembly-dashboard-war/pom.xml
assembly/codeready-workspaces-assembly-dashboard-war/src/main/webapp/assets/branding/product.json.template

Patches version of the Dashboard.
Upstream related changes were merged in https://github.com/eclipse/che/pull/16406
https://issues.redhat.com/browse/CRW-673
Not fully. I mean I've done:
```bash
export JOB_NAME="sleshche-local"
export BUILD_NUMBER=1
export GIT_COMMIT=123456
export GIT_BRANCH=patchedVersion
mvn clean install
```
and checked that the build tomcat.zip contains patched version but I have not built and deploy CRW to check if Dashboard displays it

Patch version of the Dashboard

---

dependencies/che-devfile-registry/devfiles/02_java-maven/devfile.yaml
dependencies/che-devfile-registry/devfiles/02_java-maven/meta.yaml

-  Updates existing **java-maven** devfile by replacing console-java-simple example with [vertx-health-checks-example-redhat](https://github.com/openshift-vertx-examples/vertx-health-checks-example-redhat).
-  Updates list of commands
https://issues.redhat.com/browse/CRW-412
cc @nickboldt

Replace hello-java sample with vertx-health-checks-example-redhat

---

dependencies/che-devfile-registry/devfiles/04_nodejs-configmap/devfile.yaml
dependencies/che-devfile-registry/devfiles/04_nodejs-configmap/meta.yaml
dependencies/che-plugin-registry/v3/plugins/redhat/vscode-openshift-connector/0.1.2/meta.yaml
dependencies/che-plugin-registry/v3/plugins/redhat/vscode-openshift-connector/0.1.4/meta.yaml

Set **1280Mi** as a memory limit for openshift connector plug-in. 
https://issues.redhat.com/browse/CRW-746

Set more memory for openshift connector plugin

---

dependencies/che-plugin-registry/build/scripts/write_image_digests.sh

Add debug flags in schell script to debug `write_image_digests.sh` and understand why some digests are missing
https://issues.redhat.com/browse/CRW-784

debug `write_image_digests.sh` to understand why some digests are missing

---

dependencies/che-devfile-registry/devfiles/05_cpp/devfile.yaml

Updates existing cpp devfile by replacing cpp-hello-world example with https://github.com/crw-samples/C-Plus-Plus
https://issues.redhat.com/browse/CRW-740

[CRW 2.2] Update c++ devfile to use new sample

---

dependencies/che-devfile-registry/devfiles/04_nodejs-configmap/devfile.yaml

Add debug configuration and command to run application into nodejs-configmap devfile
https://issues.redhat.com/browse/CRW-791

Add debug configuration and command to run application

---

dependencies/che-devfile-registry/devfiles/05_cpp/devfile.yaml

Reapplies redhat-developer/codeready-workspaces#277 once we're ready for 2.2 commits.
Updates existing cpp devfile by replacing cpp-hello-world example with https://github.com/crw-samples/C-Plus-Plus
https://issues.redhat.com/browse/CRW-740

[CRW 2.2] Update c++ devfile to use new sample (again)

---

dependencies/che-devfile-registry/devfiles/03_java11-gradle/devfile.yaml

-  Updates existing java-gradle devfile by replacing console-java-simple example with [gs-validating-form-input](https://github.com/crw-samples/gs-validating-form-input)
-  Updates list of commands:
https://issues.redhat.com/browse/CRW-412

[CRW 2.2] Update Gradle devfile to use new sample

---

dependencies/che-devfile-registry/devfiles/04_nodejs-mongo/devfile.yaml

Mirrors the upstream change and supports multi-arch.
Fixes https://issues.redhat.com/browse/CRW-884

Update MongoDB image from 3.4 to 3.6

---

dependencies/che-devfile-registry/devfiles/05_python/devfile.yaml

Activates global module installation mode for Python extension in Python devfile
https://issues.redhat.com/browse/CRW-886

Add 'python.globalModuleInstallation: true' pref to python devfile

---

Jenkinsfile
assembly/codeready-workspaces-assembly-dashboard-war/src/main/webapp/assets/branding/product.json.template
assembly/codeready-workspaces-assembly-main/pom.xml
assembly/codeready-workspaces-assembly-main/src/assembly/assembly.xml
assembly/pom.xml
pom.xml

Dashboard and workspace loader, which are not a part of original maven artifacts, are now built as containers, and then injected into CRWs assembly-main
CRW-881
TODO
make sure things from CRW repo are accessed after it has been checked out

Use 7.13.0 Dashboard and workspace-loader as docker containers

---

dependencies/che-plugin-registry/build/dockerfiles/rhel.Dockerfile

generate ssl cert when basing from httpd container
when upgrading from httpd-24:89 to httpd-24:91 the cert specified in ssl.conf does not exist.

generate ssl cert when basing from httpd container

---

dependencies/che-devfile-registry/devfiles/00_java-eap-maven/devfile.yaml
dependencies/che-devfile-registry/devfiles/01_java-eap-thorntail/devfile.yaml
dependencies/che-devfile-registry/devfiles/02_java-jboss-fuse/devfile.yaml
dependencies/che-devfile-registry/devfiles/02_java-maven/devfile.yaml
dependencies/che-devfile-registry/devfiles/03_spring-boot-http-booster/devfile.yaml
dependencies/che-devfile-registry/devfiles/03_vertx-http-booster/devfile.yaml

CRW-871 remove refs to stack-analysis.sh; switch to using OSBS builds of EAP 7.3.1/XP1.0; for Fuse, use JDK 8; for the rest switch to JDK 11
Change-Id: I498cea8df63b3591a4f7837e5f4fb1664f25cdb3

CRW-871 remove refs to stack-analysis.sh; switch to using OSBS builds of EAP 7.3.1/XP1.0; for Fuse, use JDK 8; for the rest switch to JDK 11

---

dependencies/che-devfile-registry/devfiles/05_go/devfile.yaml

Updates go stack's go.lintFlags parameter to use an array instead of string
Please see docs: https://github.com/microsoft/vscode-go#linter
While trying out Go stack on eclipse che hosted by Red Hat, user will recieve the folowing message:
N/A

[Che 7.13] Updated Go stack's go.lintFlags to array

---

dependencies/che-devfile-registry/devfiles/00_java-eap-maven/devfile.yaml
dependencies/che-devfile-registry/devfiles/01_java-eap-thorntail/meta.yaml
dependencies/che-devfile-registry/devfiles/01_java-thorntail/devfile.yaml
dependencies/che-devfile-registry/devfiles/01_java-thorntail/meta.yaml
dependencies/che-devfile-registry/devfiles/02_java-jboss-fuse/devfile.yaml
dependencies/che-devfile-registry/devfiles/02_java-jboss-fuse/meta.yaml
dependencies/che-devfile-registry/devfiles/02_java-maven/devfile.yaml
dependencies/che-devfile-registry/devfiles/02_java-maven/meta.yaml
dependencies/che-devfile-registry/devfiles/03_spring-boot-http-booster/devfile.yaml
dependencies/che-devfile-registry/devfiles/03_spring-boot-http-booster/meta.yaml
dependencies/che-devfile-registry/devfiles/03_vertx-http-booster/devfile.yaml
dependencies/che-devfile-registry/devfiles/03_vertx-http-booster/meta.yaml

Updates java-based stacks with new java images
- Fuse: plugin-java8-rhel8
- thorntail: plugin-java8-rhel8
- java-maven: plugin-java11-rhel8
- springboot: plugin-java8-rhel8
- vertx: plugin-java11-rhel8
- java-eap-maven: eap73-openjdk11-openshift-rhel8  **(run command doesn't work)**
https://issues.redhat.com/browse/CRW-871

Update java-based stacks to use EAP-7.3.x and plugin-java8-rhel8 images

---

dependencies/che-devfile-registry/devfiles/00_java-eap-maven/devfile.yaml
dependencies/che-devfile-registry/devfiles/00_java-eap-maven/meta.yaml

Adapt java-eap-maven to use eap73-openjdk8-openshift-rhel7
https://issues.redhat.com/browse/CRW-871

Adapt java-eap-maven to use eap73-openjdk8-openshift-rhel7

---

dependencies/che-plugin-registry/vsix.Jenkinsfile

Fixes typo in a command line, fetching the current version name
A part of this PR https://github.com/redhat-developer/codeready-workspaces/pull/316

Fix typo in a command to fetch the current version (required for Atlascode extension for VS Code )

---

dependencies/che-plugin-registry/vsix.Jenkinsfile

Runs `cd ${extensionFolder}` command in the same scope with other node commands.
Fixup for the PR https://github.com/redhat-developer/codeready-workspaces/pull/316

Change current directory withing running the NPM

---

Jenkinsfile

Hi @nickboldt  : Based on my understanding on this Jenkinsfile I have added code at line number 237, rather than creating another variable I used existing variable ${VER_CHE}. 
Modified Jenkinsfile for build-time verification of che-machine-exec and che-theia exist in plugin registry.
In maven process, if specified che.version is not in registry then it will add che version fo che-machine-exec and che-theia by running add_che_plugin.sh file.

Adding build-time verification of che-machine-exec and che-theia exist in plugin registry

---

dependencies/che-devfile-registry/devfiles/01_java-thorntail/devfile.yaml
dependencies/che-devfile-registry/devfiles/02_java-jboss-fuse/devfile.yaml
dependencies/che-devfile-registry/devfiles/02_java-maven/devfile.yaml
dependencies/che-devfile-registry/devfiles/03_java11-gradle/devfile.yaml
dependencies/che-devfile-registry/devfiles/03_java11-quarkus/devfile.yaml
dependencies/che-devfile-registry/devfiles/03_spring-boot-http-booster/devfile.yaml
dependencies/che-devfile-registry/devfiles/03_vertx-http-booster/devfile.yaml
dependencies/che-devfile-registry/devfiles/03_web-nodejs-simple/devfile.yaml
dependencies/che-devfile-registry/devfiles/04_nodejs-mongo/devfile.yaml
dependencies/che-devfile-registry/devfiles/05_cpp/devfile.yaml
dependencies/che-devfile-registry/devfiles/05_dotnet/devfile.yaml
dependencies/che-devfile-registry/devfiles/05_go/devfile.yaml
dependencies/che-devfile-registry/devfiles/05_php-cake/devfile.yaml
dependencies/che-devfile-registry/devfiles/05_php-web-simple/devfile.yaml
dependencies/che-devfile-registry/devfiles/05_python/devfile.yaml

- Makes commands numbered from all devfiles in order they should be run.
- Adds a new command to inform user to log into deployment cluster into devfiles which have 'deploy to Opneshift cluster' command
https://issues.redhat.com/browse/CRW-1046
https://issues.redhat.com/browse/CRW-1028

Update commands' names

---

dependencies/update_version.sh

Add script that can be used for the orchestrated upgrade of CRW - that updating VERSION, and the CRW images versions in registries. Only affects latest plugins in case of plugin registry
https://issues.redhat.com/browse/CRW-1096

CRW-1096 Add script for updating CRW images in registries

---

dependencies/che-devfile-registry/Jenkinsfile
dependencies/che-plugin-registry/Jenkinsfile

ensure swap_images happens after resources.tgz is expanded to prevent overwriting
CRW-1193

CRW-1193 ensure swap_images happens after resources.tgz is expanded 

---

dependencies/che-plugin-registry/v3/plugins/golang/go/0.16.1/meta.yaml

latest golang plugin should be using latest stacks-golang
fix error:
failed to fetch plugin meta.yaml from URL 'https://plugin-registry-crw.apps.qe2-s390x.psi.redhat.com/v3/plugins/ms-vscode/go/latest/meta.yaml'

latest golang plugin should be using latest stacks-golang

---

dependencies/che-devfile-registry/build/scripts/find_image.sh
dependencies/che-devfile-registry/build/scripts/swap_images.sh
dependencies/che-plugin-registry/build/scripts/find_image.sh
dependencies/che-plugin-registry/build/scripts/swap_images.sh

registry.redhat.io will always error out in brew when trying to download manifest due to no authentication, so registry-proxy.engineering.redhat.com is used instead.  Since the swap_images.sh script was using tag 1.0 instead of the actual GA release of 1.0-12 the latest internal sha was being used instead.
Have also added some additional log info to show what alternative is being used for each digest being written.
fix incorrect sha for eap xp1 image on s390x

fix incorrect sha for eap xp1 image on s390x

---

dependencies/che-devfile-registry/devfiles/03_spring-boot-http-booster/devfile.yaml

fix springboot devfile to have generateName (otherwise won't open).  Verified this is a one-off (all others have generateName).

fix spring boot devfile to have generateName

---

dependencies/che-devfile-registry/devfiles/03_spring-boot-http-booster/devfile.yaml

Fix a command  to run remote debugging in spring_boot_http_booster application.
`-Dspring-boot.run.jvmArguments` attribute should be used with the new version of spring boot (2.x.x)
https://issues.redhat.com/browse/CRW-1234

Fix the command to debug spring app

---

dependencies/che-devfile-registry/devfiles/05_php-cake/devfile.yaml
dependencies/che-devfile-registry/devfiles/05_php-web-simple/devfile.yaml

Adds a command into php devfiles to inform user to reindex workspace after installing dependencies.
https://issues.redhat.com/browse/CRW-981

Add a command into php devfile to reindex ws

---

dependencies/configbump/Jenkinsfile

fixup leading whitespace in generated rsync exclude files

fixup leading whitespace in generated rsync exclude files

---

dependencies/che-editor-intellij-community/devfiles/meta.yaml

Set up correct version of used JetBrains product and fix https://issues.redhat.com/browse/CRW-1364 by using correct volume mount.
For Idea IC 2020.2.2 correct mount path should be `/JetBrains/IdeaIC`
For Idea IC 2020.2.3 correct mount path should be `/JetBrains/ideaIC`
https://issues.redhat.com/browse/CRW-1364
N/A
N/A

Update version used IntelliJ Idea IC

---

dependencies/che-devfile-registry/devfiles/05_dotnet/devfile.yaml

Fixes the problem with dotnet debugger. Since the name of build command was changed, need to change it in debug configuration as well.

fix preLaunchTask in dotnet stack

---

dependencies/che-devfile-registry/devfiles/02_java-jboss-fuse/devfile.yaml

Update sample information for java-jboss-fuse stack. Now it will be cloned from crw-samples, this version contains a fix which make it possible to deploy the sample to OS.
https://issues.redhat.com/browse/CRW-1409

Fix sample for jboss-fuse

---

dependencies/che-plugin-registry/v3/plugins/redhat/java/0.63.0/meta.yaml
dependencies/che-plugin-registry/v3/plugins/redhat/java8/0.63.0/meta.yaml

Changes .m2 volume from /home/theia/.m2 to /home/jboss/.m2 in redhat/java and redhat/java8 plugins 
https://issues.redhat.com/browse/CRW-1418

Fix .m2 volume path

---

README.adoc

Currently most of the README is rendered as `preformatted code`:
This PR fix that.

Fix README rendering

---

dependencies/che-devfile-registry/build/scripts/swap_yamlfiles.sh

[CRW-1380](https://issues.redhat.com/browse/CRW-1380) -- add support for arch specific devfiles when building devfileregistry.  crw-jenkins updates to CRW_CI/crw-devfileregistry_2.6.jenkinsfile also needed (in separate MR)

CRW-1380 add swap_yamlfiles.sh for arch specific devfile support

---

dependencies/che-devfile-registry/build/dockerfiles/Dockerfile

Prevents errors like:
`standard_init_linux.go:211: exec user process caused "no such file or directory"`
from occurring when building with the alpine based Dockerfile.
N/A

Align Dockerfile with upstream to prevent invalid images from being built

---

dependencies/che-devfile-registry/devfiles/02_java-jboss-fuse/devfile.yaml

Replaces `jvmArguments` with `-Dspring-boot.run.jvmArguments` to run jboss-fuse sample in debug mode. Spring 2.x requires this parameter.
https://issues.redhat.com/browse/CRW-1501

Fix Run in debug mode command for Spring 2.x

---

dependencies/che-devfile-registry/build/dockerfiles/content_sets_rhel8.repo
dependencies/che-plugin-registry/build/dockerfiles/content_sets_rhel8.repo

Allows non-RH people to build the rhel.Dockerfile without being behind the Red Hat VPN.
Part of RHDEVDOCS-2513

Add skip_if_unavailable=True for content sets behind the VPN

---

dependencies/che-plugin-registry/build/dockerfiles/rhel.Dockerfile
dependencies/che-plugin-registry/build/scripts/bump_memory.sh

For https://issues.redhat.com/browse/CRW-1475 bumping up theia memory in plugin registry for power
1. As per above JIRA , we needed more memory in plugin registry image for "che-plugin-registry/v3/plugins/eclipse/che-theia/next/meta.yaml"
2. Invoke new script bump_memory.sh for power in rhel.dockerfile
Signed-off-by: Amit Ghatwal <ghatwala@us.ibm.com>

For power : bumping up memory in plugin registry 

---

dependencies/che-devfile-registry/devfiles/05_go/devfile.yaml

Fixing go devfile preferences according to upstream - https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/go/devfile.yaml#L27
Try it on workspaces.openshift.com
[![Contribute](https://raw.githubusercontent.com/redhat-developer-demos/quarkus-reactjs-postit-app/master/factory-contribute.svg)](https://workspaces.openshift.com/f?url=https://raw.githubusercontent.com/ibuziuk/codeready-workspaces/go_devfile_fixup/dependencies/che-devfile-registry/devfiles/05_go/devfile.yaml)
N/A
N/A
N/A

Fixing go devfile preferences

---

assembly/branding/product.json.template

This PR cleans up product.json in the same way as it's done for new Dashboard.
P.S. Workspace loader will be removed in a separate PR.
It follows up https://github.com/eclipse/che/pull/18549
It's done for switching to Dashboard Next https://issues.redhat.com/browse/CRW-1435

[2.8] Adapt CRW to the new dashboard

---

dependencies/che-plugin-registry/v3/plugins/che-incubator/cpptools/0.1.0/meta.yaml
dependencies/che-plugin-registry/v3/plugins/eclipse/che-theia/7.29.0/meta.yaml
dependencies/che-plugin-registry/v3/plugins/eclipse/che-theia/next/meta.yaml
dependencies/che-plugin-registry/v3/plugins/golang/go/0.16.1/meta.yaml
dependencies/che-plugin-registry/v3/plugins/ms-kubernetes-tools/vscode-kubernetes-tools/1.2.0/meta.yaml
dependencies/che-plugin-registry/v3/plugins/ms-python/python/2020.7.94776/meta.yaml
dependencies/che-plugin-registry/v3/plugins/ms-vscode/node-debug2/1.42.3/meta.yaml
dependencies/che-plugin-registry/v3/plugins/redhat-developer/che-omnisharp-plugin/0.0.6/meta.yaml
dependencies/che-plugin-registry/v3/plugins/redhat-developer/netcoredbg-theia-plugin/0.0.3/meta.yaml
dependencies/che-plugin-registry/v3/plugins/redhat/dependency-analytics/0.1.0/meta.yaml
dependencies/che-plugin-registry/v3/plugins/redhat/java/0.63.0/meta.yaml
dependencies/che-plugin-registry/v3/plugins/redhat/java11/0.69.0/meta.yaml
dependencies/che-plugin-registry/v3/plugins/redhat/java8/0.63.0/meta.yaml
dependencies/che-plugin-registry/v3/plugins/redhat/php-debugger/1.13.0/meta.yaml
dependencies/che-plugin-registry/v3/plugins/redhat/php/1.3.11/meta.yaml
dependencies/che-plugin-registry/v3/plugins/redhat/quarkus-java11/1.5.0/meta.yaml
dependencies/che-plugin-registry/v3/plugins/redhat/vscode-apache-camel/0.0.31/meta.yaml
dependencies/che-plugin-registry/v3/plugins/redhat/vscode-camelk/0.0.22/meta.yaml
dependencies/che-plugin-registry/v3/plugins/redhat/vscode-openshift-connector/0.1.5/meta.yaml
dependencies/che-plugin-registry/v3/plugins/redhat/vscode-wsdl2rest/0.0.11a/meta.yaml
dependencies/che-plugin-registry/v3/plugins/redhat/vscode-xml/0.14.0/meta.yaml
dependencies/che-plugin-registry/v3/plugins/redhat/vscode-yaml/0.11.1/meta.yaml
dependencies/che-plugin-registry/v3/plugins/sonarsource/sonarlint-vscode/1.20.1/meta.yaml
dependencies/che-plugin-registry/v3/plugins/vscode/typescript-language-features/1.49.3/meta.yaml

Adds `cpuLimit` and `cpuRequest` into plugin yamls. All values were ported from the upstream.
https://issues.redhat.com/browse/CRW-1637

Add resource limits/requests to the plugins

---

dependencies/che-devfile-registry/devfiles/03_java11-maven-quarkus/devfile.yaml

- Adds an attribute `-Dquarkus.live-reload.instrumentation=false` into run command to disable instrumentation. It is a quickfix to avoid https://github.com/quarkusio/quarkus/issues/16191
-  Marks ports 5005 and 8081 as private to avoid notifications about port listening
https://issues.redhat.com/browse/CRW-1543

Fix debugging a quarkus app

---

dependencies/che-devfile-registry/build/scripts/index.sh

Fix devfile ordering in dev environment:
- local build with podman
- build in a dogfooding Che workspace

fix(index.json): Fix devfile ordering in dev environment

---

dependencies/che-plugin-registry/v3/plugins/joaompinto/vscode-asciidoctor/2.7.7/meta.yaml

Deprecate this plugin as it doesn't seem to have a good reason for being there, and is broken.
Fixes [CRW-1701](https://issues.redhat.com/browse/CRW-1701)

Deprecate the asciidoctor-vscode plugin

---

dependencies/che-devfile-registry/build/scripts/check_mandatory_fields.sh
dependencies/che-devfile-registry/devfiles/00_java11-maven-microprofile-bootable/meta.yaml
dependencies/che-devfile-registry/devfiles/00_java11-maven-microprofile-xp2/meta.yaml
dependencies/che-devfile-registry/devfiles/00_java8-maven-eap/meta.yaml
dependencies/che-devfile-registry/devfiles/02_java8-maven-fuse/meta.yaml
dependencies/che-devfile-registry/devfiles/03_camelk/meta.yaml
dependencies/che-devfile-registry/devfiles/03_java11-maven-gradle/meta.yaml
dependencies/che-devfile-registry/devfiles/03_java11-maven-lombok/meta.yaml
dependencies/che-devfile-registry/devfiles/03_java11-maven-quarkus/meta.yaml
dependencies/che-devfile-registry/devfiles/03_java11-maven-vertx-http-booster/meta.yaml
dependencies/che-devfile-registry/devfiles/03_java11-maven-vertx/meta.yaml
dependencies/che-devfile-registry/devfiles/03_java8-maven-spring-boot-http-booster/meta.yaml
dependencies/che-devfile-registry/devfiles/04_nodejs-configmap/meta.yaml
dependencies/che-devfile-registry/devfiles/04_nodejs-mongo/meta.yaml
dependencies/che-devfile-registry/devfiles/04_nodejs-simple/meta.yaml
dependencies/che-devfile-registry/devfiles/05_cpp/meta.yaml
dependencies/che-devfile-registry/devfiles/05_dotnet/meta.yaml
dependencies/che-devfile-registry/devfiles/05_go/meta.yaml
dependencies/che-devfile-registry/devfiles/05_php-cake/meta.yaml
dependencies/che-devfile-registry/devfiles/05_php-di/meta.yaml
dependencies/che-devfile-registry/devfiles/05_python/meta.yaml

Removes redundant `globalMemoryLimit` from devfile meta.yaml as not used anymore.
Upstring PR https://github.com/eclipse-che/che-devfile-registry/pull/379
https://issues.redhat.com/browse/CRW-1703

Remove global memory limits from devfile meta.yamls

---

dependencies/che-plugin-registry/v3/plugins/sonarsource/sonarlint-vscode/1.20.1/meta.yaml

Fixes Sonarlint plugin. The plugin requires `node` which is not present in the `java11` image, so changed the image to `java8` which has `node`. Added missing args to the sidecar.
https://issues.redhat.com/browse/CRW-1604

Change sonarlint sidecar image to java8, add needed args

---

dependencies/che-plugin-registry/build.sh
dependencies/che-plugin-registry/build/dockerfiles/entrypoint.sh
dependencies/che-plugin-registry/build/dockerfiles/test_entrypoint.sh

1. Fix problems with image regexp:
- single quotes not supported
- multiline not supported
- multiple occurence
2. Adding unit tests script
Applying upstream: https://github.com/eclipse-che/che-plugin-registry/pull/937

fix(plugin-registry-entrypoint): Fix image regex should support single quote, multi line and multiple occurrences

---

.github/workflows/publish-content-push-main.yaml

Attempt to fix the `Publish Registry Content` job which can't seem to find the plugin registry contents.
CRW-1648

Explicitly use /tmp/ folder when publishing

---

dependencies/che-plugin-registry/build/dockerfiles/Dockerfile

Make sure the .htaccess file is copied in, it went missing in the recent plugin registry automation changes.
Part of CRW-1886

fix: add v3/plugins/.htaccess file back into Dockerfile

---

dependencies/che-devfile-registry/devfiles/00_java8-maven-eap/devfile.yaml

Switch to https://github.com/jboss-developer/jboss-eap-quickstarts/tree/EAP_7.3.0.GA/kitchensink-jsp instead of https://github.com/che-samples/kitchensink-example from master branch (which appears to be based on EAP 7.2.0, from 2019)
https://issues.redhat.com/browse/CRW-1709
N/A
N/A

Update jboss-eap-quickstarts sample in 00_java8-maven-eap devfile

---

dependencies/che-plugin-registry/che-theia-plugins.yaml

Remaps the `redhat/java` plugin to `redhat/java11`. Previously it was mapped to `redhat/java8`.
Fixes CRW-1892
See the JIRA issue for this ticket.

fix(java): remap redhat/java to redhat/java11

---

dependencies/che-plugin-registry/build/dockerfiles/Dockerfile
dependencies/che-plugin-registry/build/scripts/list_referenced_images.sh

Only read generated meta.yaml files instead of che-*.yaml files, and change COPY instruction for `.htaccess` file.
CRW-1886 and CRW-1898

fix: plugin registry digest writing and v3/plugins/.htaccess copy

---

dependencies/che-plugin-registry/build/scripts/write_image_digests.sh

Handle single quotes which are now present in all the image references.
CRW-1901

fix(sed): update logic in write_image_digests.sh to handle single quotes

---

product/util.groovy

To fix - https://issues.redhat.com/browse/CRW-1912 by adding a call to loginToRegistries() inside the util.bootstrap() method.
Signed-off-by: Amit Ghatwal <ghatwala@us.ibm.com>

[CRW-1912] Ensure login to registries

---

dependencies/che-plugin-registry/build/dockerfiles/Dockerfile
dependencies/che-plugin-registry/build/scripts/list_referenced_images.sh
dependencies/che-plugin-registry/build/scripts/swap_images.sh
dependencies/che-plugin-registry/build/scripts/write_image_digests.sh

Adds `--use-generated-content` argument to both `list_referenced_images.sh` and  `swap_images.sh`. Do not check generated content by default so that scripts called outside of the plugin registry build process will still work.
Fixes CRW-1916

fix(scripts): make image scripts work both pre and post meta.yaml generation

---

dependencies/che-plugin-registry/che-theia-plugins.yaml

Add a command to run executable endpoint for redhat/java8 plugin
https://issues.redhat.com/browse/CRW-1923

fix(java): make java8 plugin executable

---

dependencies/che-devfile-registry/build/scripts/index.sh
dependencies/che-devfile-registry/devfiles/03_java11-maven-quarkus/meta.yaml

Now that it's possible to use DevWorkspaces, Getting started should show Devfile v2
needs to be backported to 2.10.x branch
https://github.com/eclipse/che/issues/19341

feat: Introduce devfile v2 for quarkus getting started

---

dependencies/che-devfile-registry/build/dockerfiles/entrypoint.sh

Appends plugin registry root to icon and self links.
Pull request, fixing the same case in upstream devfile registry https://github.com/eclipse-che/che-devfile-registry/pull/420
Upstream issue https://github.com/eclipse/che/issues/19140

fix(links): Add plugin registry root at the beginning of icon and self links

---

dependencies/che-plugin-registry/che-theia-plugins.yaml

Use java8 image which contains node to fix problems with SonarLint plugin initialization 
https://issues.redhat.com/browse/CRW-1604

fix(sonarlint): use java8 image for sonarlint plugin

---

dependencies/che-plugin-registry/che-theia-plugins.yaml

Downgrade vscode-apache-camel extension to 0.0.31 since 0.0.32 cannot be initialized if VS Code API is 1.50.0
https://issues.redhat.com/browse/CRW-1951

chore: downgrade vscode-apache-camel to 0.0.31

---

dependencies/che-plugin-registry/che-theia-plugins.yaml

Skips dependency of vscode-commons extension in vscode-apache-camel extension to avoid such error:
```
Activating extension 'Tooling for Apache Camel K by Red Hat' failed: Dependent extension 'redhat.vscode-commons' is not installed.
```
https://issues.redhat.com/browse/CRW-1951

fix: skip vscode-commons in camel-lsp-client-vscode

---

product/util.groovy

Change-Id: I69bbce46bb95f9da8dc482c975e411bad65afd64
Restoring the changes from https://github.com/redhat-developer/codeready-workspaces/pull/465 that I accidentally wiped out while pushing the `crw-2-rhel-8` branch

fix(secrets): use single quotes for secrets

---

product/updateBaseImages.sh

Add option to enforce creation of PR when updating base images, to prevent unwanted direct push to target main branch
https://github.com/eclipse/che/issues/18831

feat: eclipse/che#18831 - Add option for updateBaseImages.sh to enforce PR creation

---

dependencies/che-plugin-registry/che-theia-plugins.yaml

no more declared dependency to vscode-commons (so can remove the
skipDependencies)
requires https://github.com/redhat-developer/codeready-workspaces-deprecated/pull/78
Upgrade VS Code Camel K to 0.0.26
CRW-1951
Upgrade VS Code Camel K to 0.0.26

feat CRW-1951 - Upgrade VS Code Camel K 0.0.26

---

dependencies/che-plugin-registry/che-editors.yaml

Signed-off-by: xbaran4 <pbaran@redhat.com>
Adds urlRewriteSupported attribute for theia and che-machine-exec endpoints so that they can be served on subpath instead of subdomain.
This is a backport of PR in Che upstream: https://github.com/eclipse-che/che-plugin-registry/pull/1013

feat: urlRewriteSupported attribute added for theia and machine-exec

---

dependencies/che-devfile-registry/build.sh
dependencies/che-plugin-registry/build.sh

Fix the build by adapting build.sh scripts after [removing VERSION files](https://github.com/redhat-developer/codeready-workspaces/commit/56661aa0b8e08463d874a29b63cd09fe949da32e#diff-1597e4b1db53cf9ead740724cf5be6968e40d0d6dcd5d482762fe3820f8f14bc)
N/A
N/A
N/A

fix: adapt build scripts after removing VERSION file

---

dependencies/che-devfile-registry/devfiles/05_python/devfile.yaml
dependencies/che-plugin-registry/che-theia-plugins.yaml

Signed-off-by: Sun Tan <sutan@redhat.com>
Updating python extension to
- fix jupyter notebook issues
- enabling venv that should be shared as a volume in jupyter notebook or plain python devfiles
- updated python devfile to use the venv volume
Fix https://issues.redhat.com/browse/CRW-1857
requiring https://github.com/redhat-developer/codeready-workspaces-images/pull/51 and https://github.com/redhat-developer/codeready-workspaces-deprecated/pull/76
Jupyter Notebooks native support through the Python VS Code extension

feat(python-plugin): enabling venv and jupyter notebook

---

dependencies/che-devfile-registry/build/dockerfiles/content_sets_ubi8.repo
dependencies/che-plugin-registry/build/dockerfiles/content_sets_ubi8.repo

These public facing content repos are for an image update. This allows downstream products to more easily adopt CRW. @nickboldt

Adding content repo that are public facing

---

dependencies/job-config.json
product/updateVersionAndRegistryTags.sh

- takes out the check for upstream branches and so the script updates the upstream_branch field with 7.yy.x/crw-2.yy-rhel-8 
- use CRW_VERSION to set crw-2.yy-rhel-8 branch since the passed in BRANCH is crw-2-rhel-8
- fix jq commands that broke when I added the upstream_branch field to the json
https://issues.redhat.com/browse/CRW-2203

CRW-2203, fix updateVersionAndRegistryTags.sh

---

dependencies/job-config.json

Explained in title: 2.12, 2.13, 2.x got taken out from job-config.json and caused operator jenkins builds to break because it references the devworkspace branch.
Related to https://issues.redhat.com/browse/CRW-2203

Fix: adding 2.12, 2.13 and 2.x versions back for devworkspace-controller

---

dependencies/che-plugin-registry/che-editors.yaml

Back port of https://github.com/eclipse-che/che-plugin-registry/pull/1077
Signed-off-by: Vladyslav Zhukovskyi <vzhukovs@redhat.com>
part of https://github.com/eclipse/che/issues/20460
Add idle timeout parameter to machine exec

Add idle timeout parameter to machine exec

---

dependencies/che-plugin-registry/che-theia-plugins.yaml

Signed-off-by: Igor Vinokur <vsvydenk@redhat.com>
Update the openshift authentication tool to 0.0.3 for the openshift plugin sidecar.
https://issues.redhat.com/browse/CRW-2440

chore: update OS auth plugin to 0.0.3

---

dependencies/che-plugin-registry/che-theia-plugins.yaml

Update the GitHub Pull Request plugin to 0.21.1 which uses `registerFileDecorationProvider` instead of previous `registerDecorationProvider` plugin API method.
fixes https://github.com/eclipse/che/issues/20689

chore: Update the GitHub PR plugin to 0.21.1

---

product/util.groovy

extract a kinit method we can call separate from bootstrap(); add new method for sshMountRcmGuest (used by crwctl and crw sources builds)
Change-Id: I8f4e2b5424f889df6fee57d6dc0ea6de21c739f6
N/A
https://issues.redhat.com/browse/CRW-1919
```
#!/usr/bin/env groovy
import groovy.transform.Field
timeout(120) {
node("rhel83") { 
stage ("Build on rhel83") {
currentBuild.description="Run on " + NODE_NAME + " (" + NODE_LABELS + ")"
wrap([$class: 'TimestamperBuildWrapper']) {
sh('curl -sSLO https://raw.githubusercontent.com/redhat-developer/codeready-workspaces/crw-2-rhel-8/product/util.groovy')
def util = load "${WORKSPACE}/util.groovy"
withCredentials([
string(credentialsId:'crw_devstudio-release-token', variable: 'GITHUB_TOKEN'), …
```

fix: feat: chore: extract a kinit method we can call it separately from longer slower bootstrap()

---

dependencies/che-plugin-registry/che-theia-plugins.yaml

Adds volume of `/home/theia/.kube` into the container where OS connector plugin is running
https://issues.redhat.com/browse/CRW-2556
N/A
N/A
N/A

chore: add voulumeMount for .kube folder

---

dependencies/che-plugin-registry/che-theia-plugins.yaml

Adds sidecar information for openshift-auth plugin. This fix is also needed to merge plugins in one sidecar.
https://github.com/eclipse/che/issues/20915
N/A
N/A

feat:add sidecar for che-theia-os-auth plugin

---

dependencies/che-devfile-registry/devfiles/03_java11-maven-gradle/meta.yaml

Introduces devfile version 2 for Java+Gradle stack. A new devfile is located here https://github.com/crw-samples/gs-validating-form-input/blob/devfilev2/devfile.yaml. 
https://issues.redhat.com/browse/CRW-2412

feat(devfile): Add link to devfile v2 for Java+Gradle

---

dependencies/che-devfile-registry/devfiles/00_java11-maven-microprofile-xp3/meta.yaml

Adds a link to devfile version 2 for microprofile-xp3 sample. 
New devfile uses **mergeImage** sidecar-policy attribute, because we need `registry.redhat.io/jboss-eap-7/eap-xp3-openjdk11-openshift-rhel8` image to run WildFly server and `registry.redhat.io/codeready-workspaces/plugin-java11-rhel8` to run vscode-java plugin without problems.
The link to the devfile: https://github.com/crw-samples/microprofile-quickstart/blob/devfilev2/devfile.yaml
https://issues.redhat.com/browse/CRW-2412

feat(devfile): Add a link to devfile v2 for microprofile-xp3 sample

---

dependencies/che-devfile-registry/devfiles/00_java8-maven-eap/meta.yaml

Adds a link to devfile v2 in java8-maven-eap
The link to the devfile: https://github.com/crw-samples/jboss-eap-quickstarts/tree/devfilev2

feat(devfile): add link to devfile v2 for java8-maven-eap

---

dependencies/che-plugin-registry/che-theia-plugins.yaml

Signed-off-by: Thomas Mäder <tmader@redhat.com>
Update VS Code Java to version 0.82
https://issues.redhat.com/browse/CRW-2590

Update vscode-java to 0.82

---

dependencies/che-devfile-registry/devfiles/00_java11-maven-microprofile-bootable/meta.yaml

Introduces devfile v2 for microprofile-bootable
A link to the devfile v2:  https://github.com/crw-samples/microprofile-quickstart/tree/devfilev2-bootable

feat(devfile): Add link to devfile v2 for microprofile-bootable

---

dependencies/che-devfile-registry/devfiles/03_java11-maven-vertx/meta.yaml

Introduces devfile version 2 for Java Vertx
Link to devfile: https://github.com/crw-samples/vertx-health-checks-example-redhat/blob/devfilev2/devfile.yaml

feat(devfile): Add link to java-vertx devfile v2

---

dependencies/che-devfile-registry/devfiles/05_dotnet/meta.yaml

Adds link to devfile version 2 for dotnet stack. 
omnisharp and netcoredbg plugins have an issue with the initialization, it should be fixed by https://issues.redhat.com/browse/CRW-2456
Link to the devfile: https://github.com/crw-samples/dotnet-web-simple/blob/devfilev2/devfile.yaml

feat(devfile): Add link to devfile v2 for dotnet stack

---

dependencies/che-plugin-registry/che-theia-plugins.yaml

Adds name for plugins' sidecars
It is needed to migrate nodejs-configmap sample to devfile v2 https://issues.redhat.com/browse/CRW-2539

feat(plugins): add name field into sidecars

---

dependencies/che-devfile-registry/devfiles/04_nodejs-configmap/meta.yaml

Adds link to devfile version 2 for nodejs-configmap sample. 
Link to the devfile: https://github.com/crw-samples/nodejs-configmap/blob/devfilev2/devfile.yaml
Devfile contains `che-theia.eclipse.org/sidecar-policy: mergeImage` because for now we don't have one image with oc (needed for openshift-connector plugin) and npm (needed for typescript-language-features)

feat(devfile):introduce devfile v 2 for nodejs-configmap sample

---

dependencies/che-devfile-registry/devfiles/06_idea_rhel/devfile.yaml

Fix 06_idea_rhel devfile to reference latest meta.yaml
IntelliJ IDEA **meta.yaml** is placed into **v3/plugins/che-incubator/intellij-community/latest** directory in CRW 2.15.0.ER-01-27 plugin registry.
Fixes https://issues.redhat.com/browse/CRW-2686

Fix 06_idea_rhel devfile to reference latest meta.yaml

---

dependencies/che-plugin-registry/build/dockerfiles/Dockerfile

This will aide in downstream projects to consume much easier and include their own plugins.
@nickboldt please review.
Upstream contribution
https://github.com/eclipse-che/che-plugin-registry/pull/1190
Updates Dockerfile to copy multiple plugins and images.
N/A
N/A
N/A

CHORE: An update to copy all plugins and images

---

dependencies/che-devfile-registry/build.sh
dependencies/che-devfile-registry/build/dockerfiles/Dockerfile
dependencies/che-devfile-registry/build/scripts/generate_devworkspace_templates.sh

Signed-off-by: Igor Vinokur <ivinokur@redhat.com>
In order to fix the Jenkins build, move the devfile v2 templates generation script to `./build.sh`
https://issues.redhat.com/browse/CRW-2500

fix: Move devfile templates generation to build.sh

---

dependencies/che-devfile-registry/build/scripts/list_yaml.sh

Expand the `list_yaml.sh` script, which generate a list of files for the `swap_images.sh` script, with devfile v2 templates to support images for different architectures. 
https://issues.redhat.com/browse/CRW-2578

chore: Include devfile v2 templates to swap_images list

---

dependencies/che-devfile-registry/devfiles/03_java11-maven-quarkus/devfile.yaml

Use [crw-samples](https://github.com/crw-samples) org to clone quarkus sample
The latest version of Quarkus is required maven [3.8.1) but **plugin-java11-rhel8** image provides 3.6.3 
We can update Maven in UDI for the next releases
Fixes https://issues.redhat.com/browse/CRW-2732

chore: use crw-samples org for quarkus sample

---

dependencies/che-plugin-registry/che-theia-plugins.yaml

notably, it is a release which has a repeatable (reproducible?) build
Signed-off-by: Aurélien Pupier <apupier@redhat.com>
Upgrade VS Code Language Support for Apache Camel to 0.1.5
https://issues.redhat.com/browse/CRW-2749

chore: CRW-2749 - upgrade VS Code Language Support for Camel to 0.1.5

---

dependencies/che-devfile-registry/devfiles/02_java8-maven-fuse/devfile.yaml

Removes redundant MAVEN_OPTS from the 1. Build command to avoid overriding  
https://issues.redhat.com/browse/CRW-2752

chore: remove redundant MAVEN_OPTS from build command

---

product/manifest/get-3rd-party-deps-manifests.sh

Fix manifest collection for python dependencies, using venv instead of virtualenv
https://issues.redhat.com/browse/CRW-2763

fix: fix manifest collection for Python

---

dependencies/che-devfile-registry/devfiles/03_java11-maven-vertx-http-booster/devfile.yaml
dependencies/che-devfile-registry/devfiles/03_java8-maven-spring-boot-http-booster/devfile.yaml

Cleanups maven commands in  Java Vert.X and Java Sprint Boot devfiles by removing redundant parameters
https://issues.redhat.com/browse/CRW-2486

feat(devfile): Cleanup mvn commands

---

dependencies/che-devfile-registry/build/dockerfiles/Dockerfile

Signed-off-by: Igor Vinokur <ivinokur@redhat.com>
Remove redundant `COPY ./versions.json /build/` from devfile-registry Dockerfile as a leftover.
The `versions.json` is read from `./build.sh` script and it is not used in the `Dockerfile` any more.

fix: Remove redundant COPY from devfile-registry Dockerfile

---

dependencies/che-devfile-registry/devfiles/00_java11-maven-microprofile-bootable/meta.yaml

Changes the link to devfile v2 for microprofile-bootable sample. 
Now for microprofile-bootable devfile 2 we have own sample repo: https://github.com/crw-samples/microprofile-quickstart-bootable 
Needs for https://issues.redhat.com/browse/CRW-2742

feat(devfile): update link to microprofile-bootable devfile v2

---

product/tagRelease.sh

Add logic to create branches of CRW samples. 
If the script will be executed in **crw-2.16-rhel-8** branch, in crw samples we should have **2.16-devfilev2** branches
https://issues.redhat.com/browse/CRW-2742

feat(prod): add script to create branches for crw-samples

---

dependencies/che-devfile-registry/devfiles/02_java11-maven-fuse/devfile.yaml
dependencies/che-devfile-registry/devfiles/02_java11-maven-fuse/meta.yaml

requires https://github.com/crw-samples/fuse-rest-http-booster/pull/4

CRW-2591 - migrate Camel on springboot stack to java 11

---

dependencies/che-devfile-registry/build/dockerfiles/entrypoint.sh
dependencies/che-devfile-registry/build/dockerfiles/test_entrypoint.sh
dependencies/che-devfile-registry/build/scripts/list_referenced_images.sh

- Look at devworkspace-*.yaml files to collect used images which will be injected into the image with digest be crw-operator at build time
- Replace tag with digest in devworkspace-*.yaml files at runtime 
https://issues.redhat.com/browse/CRW-2887

chore:set and use RELATED_IMAGE envs for devworskpaces

---

dependencies/che-devfile-registry/build/dockerfiles/entrypoint.sh
dependencies/che-devfile-registry/build/dockerfiles/test_entrypoint.sh
dependencies/che-devfile-registry/build/scripts/generate_devworkspace_templates.sh

Skip spaces in the project location in devworkspace templates
https://issues.redhat.com/browse/CRW-2908

fix: don't use spaces in the project's location

---

product/filterIIBForDevSpaces.sh

Adds script `filterIIBForDevSpaces.sh` that can be used to pull DS/DWO/WTO and optionally CRW from an IIB image and build a new index image that contains only those operators. Note downloading the IIB and rendering it can take multiple minutes since it's so large.
The new index uses the exact same images as the IIB image, so it is suitable for testing Dev Spaces as you would from the IIB itself.
Usage:
```
./filterIIBForDevSpaces.sh \
--iib registry-proxy.engineering.redhat.com/rh-osbs/iib:225370 \
--tag test-index-image:dev
```
Results in
if this index is deployed as a CatalogSource
N/A

Add script for extracting DS/DWO/WTO from IIB image

---

.github/workflows/plugin-registry-build.yaml
.github/workflows/plugin-registry-pr-check-build.yaml

Avoid cloning `quay.io/devspaces/pluginregistry-rhel8:next-gh-action` image before the image build to fix GitHub action, it seems this image is not needed for the build process.

fix: remove redundant docker pull from GA

---

dependencies/che-plugin-registry/build/dockerfiles/entrypoint.sh
dependencies/che-plugin-registry/build/dockerfiles/test_entrypoint.sh

Replaces `relative:extension` with plugin-registry internal URL at runtime in the plugin registry container
https://issues.redhat.com/browse/CRW-2973

chore: use internal url in plugin meta.yaml to download vsx

---

dependencies/che-plugin-registry/che-editors.yaml

Update Devfile definition for IntelliJ IDEA Community Edition 2022.1 version.
Uses downstream UDI as runtime image.
To test changes it is enough to create the workspace from the following repository: 
```
https://github.com/vzhukovs/demo-repository/tree/idea-rhel8
```
Signed-off-by: Vladyslav Zhukovskyi <vzhukovs@redhat.com>
https://issues.redhat.com/browse/CRW-2977

Update Devfile definition for idea-rhel8

---

dependencies/che-devfile-registry/build/scripts/swap_yamlfiles.sh

Marks meta.yaml as removed if devfile folder contains devfile.yaml.**arch** file. Where **arch** could be ppc64le or s390x.
When meta.yaml is marked as removed, the devfile should not be shown on the Create workspace view.
https://issues.redhat.com/browse/CRW-3034

fix: remove meta.yaml if devfile.yaml.${arch} exists

---

dependencies/che-plugin-registry/che-theia-plugins.yaml

Remove deprecated vscode-wsdl2rest plugin
https://github.com/eclipse/che/issues/21457

chore:remove deprecated wsdl2rest

---

dependencies/che-devfile-registry/devfiles/06_idea_rhel/meta.yaml

Since we don't want to have samples which describe some special editor in the default devfile registry, IntelliJ IDEA Community Edition sample was removed from the devfile registry. It is still possible to use IntelliJ IDEA editor by following **Selecting an IDE** chapter from the documentation.
https://issues.redhat.com/browse/CRW-3014

chore: remove intellij sample from the registry

---

dependencies/che-plugin-registry/che-theia-plugins.yaml

Update id for Quarkus plugin accordingly to upstream https://github.com/eclipse-che/che-plugin-registry/blob/main/che-theia-plugins.yaml#L222 
Quarkus plugins cannot be installed in Quarkus base workspace
https://issues.redhat.com/browse/CRW-2993

fix: set correct id for vscode-quarks plugin

---

dependencies/che-plugin-registry/che-editors.yaml

Increases idle timeout to 30 minutes in workspaces that use Theia editor
https://issues.redhat.com/browse/CRW-3154

chore: increase idle timeout to 30 minutes

---

dependencies/job-config.json

Signed-off-by: Roman Nikitenko <rnikiten@redhat.com>
I'm working on productization vscode as an OpenShift Dev Spaces editor.
It works for linux x64 platform, but it doesn't for `ppc64` and `s390x`.
I'm going to work on some adaptation fro `ppc64` and `s390x` platforms within `devspaces-3.2-rhel-8` branch and test my changes using `code_3.x` job on jenkins.
So, let's change the target branch for `code_3.x`.
https://issues.redhat.com/browse/CRW-2744

Temporary change target for 3_x Code

---

dependencies/che-plugin-registry/che-editors.yaml

Signed-off-by: David Kwon <dakwon@redhat.com>
This PR is meant for Dev Spaces 3.2.
Removes the --idle-timeout from the theia editor since the idle timeout is now being [read as an environment variable](https://github.com/eclipse-che/che-machine-exec/pull/208) set by [Che + DWO](https://github.com/eclipse-che/che-operator/pull/1443)
This change is part of https://github.com/eclipse/che/issues/21390

chore: remove `--idle-timeout` for che-theia editor since timeout is read from environment variable

---

dependencies/che-plugin-registry/che-editors.yaml

Use 3.1 tag of images in the Che code editor
https://issues.redhat.com/browse/CRW-2288

fix: use 3.1 tag for Code editor

---

dependencies/che-plugin-registry/che-theia-plugins.yaml

Clean up unneeded GOPATH entry (comment from https://github.com/devspaces-samples/golang-health-check/pull/1#pullrequestreview-1050615604)
CRW-3103

fix: clean up unused GOPATH env

---

dependencies/che-plugin-registry/che-theia-plugins.yaml

Updates fabric8-analytics plugin to 0.3.6
[screencast-nimbus-capture-2022.08.11-12_27_42.webm](https://user-images.githubusercontent.com/1271546/184846431-f8bc2632-6848-4398-9de5-0ced916ce9e1.webm)
**NOTES:**
_The plugin has a problem in Che-Theia editor, when generate the report by using project tree at the first time. To workaround this problem try to generate the report by using a command: click F1 and select Dependency Analytics: Stack Report... Then it will be possible to execute the command from the project tree as well._
https://issues.redhat.com/browse/CRW-2208

feat: update fabric8-analytics plugin to 0.3.6

---

dependencies/che-plugin-registry/build/dockerfiles/Dockerfile
dependencies/che-plugin-registry/build/dockerfiles/entrypoint.sh
dependencies/che-plugin-registry/build/scripts/import_vsix.sh

Tying to a Brew build. These changes to avoid running openvsx server application and postgresql during the docker build.
All initialization logic was moved to the entrypoint.sh
https://issues.redhat.com/browse/CRW-3295

chore: run openvsx-server and postgres from entrypoint.sh only

---

product/query-pulp.sh

Add script query-pulp.sh to make process of searching for pulp repos easier. For example
```
./query-pulp.sh 'ocp-tools.*rhel-8.*x86_64'
```
prints
```jsonc
//...
{"display_name":"ocp-tools-4_DOT_11-for-rhel-8-x86_64-debug-rpms","content_set":"ocp-tools-4.11-for-rhel-8-x86_64-debug-rpms","repo_url":"http://rhsm-pulp.corp.redhat.com/content/dist/layered/rhel8/x86_64/ocp-tools/4.11/debug"}
{"display_name":"ocp-tools-4_DOT_11-for-rhel-8-x86_64-rpms","content_set":"ocp-tools-4.11-for-rhel-8-x86_64-rpms","repo_url":"http://rhsm-pulp.corp.redhat.com/content/dist/layered/rhel8/x86_64/ocp-tools/4.11/os"}
{"display_name":"ocp-tools-4_DOT_11-for-rhel-8-x86_64-source-rpms","content_set":"ocp-tools-4.11-for-rhel-8-x86_64-source-rpms","repo_url":"http://rhsm-pulp.corp.redhat.com/content/dist/layered/rh …
```

Add query-pulp.sh script to make searching for content_sets easier

---

.github/workflows/vsix-definition-pr-check.yaml
dependencies/che-plugin-registry/build/scripts/test/validate_vsix_list.sh

Add GH PR check to validate the definition of VS Code extensions
https://issues.redhat.com/browse/CRW-3477

chore: add GH PR check to validate list of vsix files definition

---

dependencies/che-plugin-registry/build/dockerfiles/Dockerfile

add -Xmx2048m to JVM_ARGS to avoid java out of memory error when run openvsx server.
The default value is 1024m
https://issues.redhat.com/browse/CRW-3295

chore: add -Xmx2048m to JVM_ARGS for running openvsx server

---

dependencies/che-plugin-registry/openvsx-sync.json

Add vscode.html-language-features extension into the local plugin registry, it is required by latest redhat.vscode-quarkus extension
https://issues.redhat.com/browse/CRW-3593

chore: add vscode.html-language-features extension

---

dependencies/che-plugin-registry/che-editors.yaml

Adds container-contribution attribute for VS Code and Theia editors.
**_NOTE_: The IDEA editor wasn't changed**
https://issues.redhat.com/browse/CRW-3612

chore: add container-contribution attribute into the editor definition

---

dependencies/che-devfile-registry/.gitignore
dependencies/che-devfile-registry/build.sh
dependencies/che-devfile-registry/build/scripts/generate_devworkspace_templates.sh
dependencies/che-devfile-registry/build/scripts/index.sh
dependencies/che-devfile-registry/versions.json

Uses [che-devworkspace-generator tool](https://github.com/eclipse-che/che-devfile-registry/tree/main/tools/devworkspace-generator) to generate DevWorkspaces with container contribution attributes.
For more details see the upstream PR: 
https://github.com/eclipse-che/che-devfile-registry/pull/690
https://issues.redhat.com/browse/CRW-3613

chore: generate devworkspaces by devworkspace-generator tool

---

dependencies/che-plugin-registry/build/dockerfiles/application.yaml

Disables ElasticSearch for built-in open-vsix server.
It is required to do after rebasing of https://github.com/che-incubator/che-openvsx/tree/che-openvsx
With this fix all the built-in extensions are not marked as installing anymore
Docker image to test **quay.io/vgulyy/pluginregistry-rhel8:crw-3544**
https://issues.redhat.com/browse/CRW-3544
https://issues.redhat.com/browse/CRW-3506

fix: disable ElasticSearch for openvsix registry

---

dependencies/che-plugin-registry/che-editors.yaml

Increase memoryLimit for che-code-injector component to 256Mi
https://github.com/eclipse/che/issues/21719

chore: increase memoryLimit for che-code-injector component

---

dependencies/che-plugin-registry/che-editors.yaml

It removes the unneeded security token for che-code main endpoint.
https://github.com/eclipse/che/issues/21772
https://github.com/eclipse-che/che-plugin-registry/pull/1562

chore:remove vscode main endpoint path

---

dependencies/che-plugin-registry/che-editors.yaml

1. Marks `idea-rhel8` component of IDEA editor as container contribution.
2. Replaces `app.kubernetes.io/component: che-rhel8-injector` on `app.kubernetes.io/component: che-rhel8-runtime` to be consistent with `che-code` where everything works without issues
https://github.com/eclipse/che/issues/21878
Depends on https://github.com/eclipse/che/issues/21738

fix: mark idea-rhel8 component as container-contribution

---

dependencies/che-devfile-registry/build.sh
dependencies/che-devfile-registry/build/scripts/generate_devworkspace_templates.sh
dependencies/che-devfile-registry/build/scripts/index.sh

Use `editor-entry:che-incubator/che-code/latest` to generate DWs instead of `editor-entry:che-incubator/che-code/insiders`
**_NOTE_**: this PR depends on https://github.com/redhat-developer/devspaces/pull/885 and should be merge after
https://issues.redhat.com/browse/CRW-3568

chore: generate DWs with VS Code latest

---

dependencies/che-devfile-registry/build/dockerfiles/entrypoint.sh
dependencies/che-devfile-registry/build/dockerfiles/test_entrypoint.sh

Updates entrypoint.sh to correctly replace  INTERNAL_URL with value of CHE_DEVFILE_REGISTRY_INTERNAL_URL.
The problem was caused by [replacing a library that generated devworkspaces](https://github.com/redhat-developer/devspaces/pull/870). 
Now it has the same format as in [upstream](https://github.com/eclipse-che/che-devfile-registry/blob/main/build/dockerfiles/entrypoint.sh#L142) 
https://issues.redhat.com/browse/CRW-3941

fix: update INTERNAL_URL pattern to be replaced

---

product/tagRelease.sh

For devspaces samples, a floating tag 'latest' will exist that will point to the latest release version of the sample
When tagging release, samples projects will have the 'latest' tagged updated with the release version (except for the cases, when a "lower" bugfix version like 3.5.1 gets released, when 3.6.0 already exists)
https://issues.redhat.com/browse/CRW-3805

feat: add latest floating tag for DevSpace Samples during release tagging process

---

dependencies/che-plugin-registry/build/scripts/download_vsix.sh

Most of the VS Code extensions provide only one link for downloading, for example [ms-python.python](https://open-vsx.org/api/ms-python/python/). 
But there are extensions with several links for downloading (depending on a target platform), for example [redhat.java](https://open-vsx.org/api/redhat/java/1.14.0):
```json
"downloads": {
"linux-x64": "https://open-vsx.org/api/redhat/java/linux-x64/1.14.0/file/redhat.java-1.14.0@linux-x64.vsix",
"win32-x64": "https://open-vsx.org/api/redhat/java/win32-x64/1.14.0/file/redhat.java-1.14.0@win32-x64.vsix",
"darwin-x64": "https://open-vsx.org/api/redhat/java/darwin-x64/1.14.0/file/redhat.java-1.14.0@darwin-x64.vsix",
"darwin-arm64": "https://open-vsx.org/api/redhat/java/darwin-arm64/1.14.0/file/redhat.java-1.14.0@darwin-arm64.vsix",
"universal": …
```

chore: use universal download link to download VS Code extensions

---

.github/workflows/plugin-registry-build.yaml
.github/workflows/plugin-registry-pr-check-build-publish-content.yaml
.github/workflows/plugin-registry-pr-check-build.yaml
.github/workflows/pr-check-linelint.yaml

Hi!
Following the [GH Action Security Hardening](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions) guide we should use the commit SHA instead of the `branch` or `tag` for any third-party untrusted action.
This PR was submitted by a script.

Pin 3rd-party actions to SHA1

---

dependencies/che-devfile-registry/build.sh
dependencies/che-devfile-registry/build/scripts/generate_devworkspace_templates.sh
dependencies/che-devfile-registry/build/scripts/index.sh

Generates DevWorkspaces with che-code:insiders editor to support che-code:insiders as a default editor that was set in the older DS versions.
https://issues.redhat.com/browse/CRW-4074

fix: generate devworkspaces with che-code:insiders

---

dependencies/job-config.json

Update CSV_VERSION_PREV to 3.5.0 for 3.6 and 3.x branches.
https://issues.redhat.com/browse/SPMM-12230

Update CSV_VERSION_PREV to 3.5.0 for 3.6 and 3.x branches.

---

dependencies/che-plugin-registry/che-editors.yaml

Rename `preStart` che-theia command.
We need this change because of upstream changes: https://github.com/eclipse-che/che-plugin-registry/pull/1613
Related to https://github.com/eclipse/che/issues/22071

fix: Do not duplicate che-theia commands

---

dependencies/che-plugin-registry/che-editors.yaml

Use post-start event instead of command to start VS Code
Upstream changes: https://github.com/eclipse-che/che-plugin-registry/pull/1566
https://github.com/eclipse/che/issues/21879

feat: Use post-start event to start VS Code

---

dependencies/che-plugin-registry/che-editors.yaml

Use post-start event instead of command to start IntelliJ IDEA.
Upstream changes: https://github.com/eclipse-che/che-plugin-registry/pull/1623
https://github.com/eclipse/che/issues/22034

feat: Use post-start event to start JetBrains IDE

---

product/ghira/ghira

fix: chore: Release Note Text custom field ID has changed from customfield_12310211 to customfield_12317313 (was causing 400 error in jenkins and local run);
also CRW-4151 - add Affects = Release Notes to these generated issues
Change-Id: I1d282a91d80c740c232c190647ce69e3dd662fd5
N/A
N/A

fix: chore: CRW-3830 Release Note Text custom field ID changed; also CRW-4151 add Affects = Release Notes

---

dependencies/che-devfile-registry/versions.json

bump evworkspace generator tool from 0.0.1-c8bd5c0 to 0.0.1-638fadc
https://github.com/eclipse/che/issues/22149

feat:bump devworkspace generator tool

---

dependencies/che-plugin-registry/build/scripts/download_vsix.sh

Some vscode extensions provide metadata with vscode engine version that contains `>=` (for example https://open-vsx.org/api/stylelint/vscode-stylelint/latest)
This PR removes `>=` before comparing wit Che Code version
https://issues.redhat.com/browse/CRW-4165

feat: remove >= from the engine's version before comparing

---

dependencies/che-plugin-registry/che-editors.yaml

Changes a display name of Che Idea editor to mark it as a tech preview.
**IntelliJ IDEA Community (Technology Preview)**
These changes will be shown on the User Dashboard when open editor's drop-down list:
https://issues.redhat.com/browse/CRW-4139

chore: add Tech Preview info for IDEA editor in the User Dashboard

---

product/tagRelease.sh

Adds devspaces-vscode-extensions since it has been redesigned to follow the devspaces-3.x-rhel-8 branching convention.
The jenkins jobs for non 3.x branches breaks when I forget to manually create a new branch.

Update tagRelease.sh to include devspaces-vscode-extensions

---

dependencies/che-plugin-registry/openvsx-sync.json

Ansible sample requires [ms-python.black-formatter extension](https://github.com/devspaces-samples/ansible-devspaces-demo/blob/devspaces-3.7-rhel-8/.vscode/extensions.json#L6) but the embedded plugin registry doesn't provide it. 
This PR adds ms-python.black-formatter extension into the embedded plugin registry
https://issues.redhat.com/browse/CRW-4359

feat(extensions): add ms-python.black-formatter extension

---

dependencies/che-plugin-registry/build.sh
dependencies/che-plugin-registry/build/dockerfiles/openvsx-builder.Dockerfile
dependencies/che-plugin-registry/build/scripts/download_vsix.sh

Gets che-code version that is used in the carrent version of DS to download vscode extension that are supported by the specific editor version
Could be tested with **quay.io/vsvydenk/pluginregistry-rhel8:3.7**
The output from the build process:
```
....
Scripts branch=devspaces-3.7-rhel-8
Che Code version=1.79.0
Skipping https://open-vsx.org/api/ms-python/python/latest, it is not compatible with VS Code editor 1.79.0
Skipping https://open-vsx.org/api/ms-python/python/2023.10.1, it is not compatible with VS Code editor 1.79.0
Skipping https://open-vsx.org/api/ms-python/python/2023.10.0, it is not compatible with VS Code editor 1.79.0
Downloading https://open-vsx.org/api/ms-python/python/2023.8.0/file/ms-python.python-2023.8.0.vsix into ms-python folder...
...
``` …

feat(extensions): provide appropriate version of che-code to download valid extensions

---

dependencies/che-plugin-registry/build/scripts/import_vsix.sh

Signed-off-by: Valeriy Svydenko <vsvydenk@redhat.com>
Clean some temporary files to avoid them to be stored in the image
https://issues.redhat.com/browse/CRW-4347
N/A
N/A

fix: cleanup vsix extensions after publishing into the embedded plugin registry

---

.devfile.yaml
.vscode/extensions.json
dependencies/che-plugin-registry/build/dockerfiles/Dockerfile
dependencies/che-plugin-registry/patch-cluster.sh

Introduces devfile.yaml with commands that allow to verify changes made in the plugin registry.
It is important to have an access to modify CheCluster definition on OS cluster
Only one extension in the list of the embedded plugin registry:
Rresult of the changes:
Related issue: https://github.com/eclipse/che/issues/22243

chore: add devfile.yaml to work with plugin registry

---

dependencies/che-plugin-registry/build/dockerfiles/Dockerfile
dependencies/che-plugin-registry/build/dockerfiles/openvsx-builder.Dockerfile
dependencies/che-plugin-registry/build/dockerfiles/ovsx-installer.Dockerfile
dependencies/che-plugin-registry/build/dockerfiles/rhel.install.sh
dependencies/che-plugin-registry/build/scripts/import_vsix.sh
dependencies/che-plugin-registry/openvsx-sync.json

Updates plugin registry to use the latest version of openvsx-server provided in https://github.com/che-incubator/che-openvsx/pull/5.
Next tools are going to be updated:
- java to 17
- postgresql to 15
- ovsx to 0.8.2
Remove deprecated redhat.project-initializer extension
https://issues.redhat.com/browse/CRW-4589
N/A
N/A

chore: upgrade plugin reg to use latest openvsx-server

---

dependencies/che-devfile-registry/build/dockerfiles/Dockerfile
dependencies/che-plugin-registry/build/dockerfiles/Dockerfile

Filtering logs on httpd servers for plugin and devfile registries to skip logs that are responses of OS health checkers
**Devfile registry:**
**Plugin registry:**
- Deploy DS
- Update devspaces CR to use custom images for devfile and plugin registries:
```
devfileRegistry:
deployment:
containers:
- image: quay.io/vsvydenk/devfileregistry-rhel8:1
......
pluginRegistry:
deployment:
containers:
- image: quay.io/vsvydenk/pluginregistry-rhel8:1
```
- Wait when plugin and devfile registries pods will be restarted
- Check logs of the plugin and devfile registries pods from the OS console
- From the logs you shouldn't see messages like
```
"GET /devfiles/ HTTP/1.1" 200 8444 "-" "kube-probe/1.25"
"GET /v3/plugins/ HTTP/1.1" 200 1231 "http://10.128.151.66:8080/plugins/" "kube-probe/1.26"
``` …

chore: update httpd custom logging to filter health checker responses

---

product/updatePNCBuildConfigs.sh

The arguments for cloning have changed. 
--scm-revision is now --scmRevision
--product-version-id is gone
@nickboldt there is now a --profile option but I'm still researching that so for now I've just taken out product version id and fixed scm revision.

Fix arguments in updatePNCBuildConfigs.sh

---

dependencies/che-plugin-registry/build/dockerfiles/Dockerfile
dependencies/che-plugin-registry/build/dockerfiles/entrypoint.sh
dependencies/che-plugin-registry/build/scripts/import_vsix.sh

Instead of publishing VSCode extensions at plugin registry runtime, it publishes them at buildtime (during the image's build).
It improves the time of starting the plugin registry pod and the memory usage of the pod.
https://issues.redhat.com/browse/CRW-4650
N/A
N/A

feat: publish vscode extensions at build time

---

dependencies/che-plugin-registry/openvsx-sync.json

Removes built-in js-debug extension from the list of embedded extensions
https://issues.redhat.com/browse/CRW-4817
N/A

chore: remove built-in js-debug extension

---

dependencies/job-config.json
product/updateVersionAndRegistryTags.sh

The value of DS version should be wrapped in quotes to parse it correct by jq.
Some scripts use `jq -r '.Version' "${jobconfigjson}"` to get version of DS, without quotes we get 3.1 instead of 3.10.
Fixes the plugin registry build

chore:wrap DS version in quotes

---

dependencies/che-plugin-registry/openvsx-sync.json

Adds ms-dotnettools.vscode-dotnet-runtime extension into the list of embedded extensions as it is required by the latest version of muhammad-sammy.csharp
https://issues.redhat.com/browse/CRW-4835

chore: add vscode-dotnet-runtime extension

---

dependencies/che-plugin-registry/build/scripts/download_vsix.sh
dependencies/che-plugin-registry/openvsx-sync.json

Backports changes from https://github.com/redhat-developer/devspaces/pull/1005 into DS 3.9
Use versions instead of allVersions to find latest compatible extensions
Fix extensions' names
https://issues.redhat.com/browse/CRW-4593

feat: use versions to find the latest greatest extension

---

dependencies/che-devfile-registry/build/dockerfiles/Dockerfile

chore: devfile registry should return index file by /index path
Backport changes from https://github.com/eclipse-che/che-devfile-registry/pull/772
https://github.com/eclipse/che/issues/22454

chore: devfile registry should return index file by /index path

---

dependencies/job-config.json

Move slack_notification to Management Jobs and use the disabled field since it can be used for both enabling the jobs and determining whether to automatically send the slack message.

make slack notification consistent

---

product/getCommitSHAForTag.sh

It fixes source URL generated by getCommitSHAForTag.sh in https://github.com/redhat-developer/devspaces/blob/devspaces-3-rhel-8/dependencies/LATEST_IMAGES_COMMITS.
Source URL before: [https://pkgs.devel.redhat.com/**git/cgit**/containers/devspaces-operator/commit?id=13f18757a803a8144e5e4b2ddf2b6a71601af1d1](https://pkgs.devel.redhat.com/git/cgit/containers/devspaces-operator/commit?id=13f18757a803a8144e5e4b2ddf2b6a71601af1d1)
Expected source URL: [https://pkgs.devel.redhat.com/**cgit**/containers/devspaces-operator/commit?id=13f18757a803a8144e5e4b2ddf2b6a71601af1d1](https://pkgs.devel.redhat.com/cgit/containers/devspaces-operator/commit?id=13f18757a803a8144e5e4b2ddf2b6a71601af1d1)

Fix source url in the output of product/getCommitSHAForTag.sh

---

dependencies/che-devfile-registry/deploy/openshift/devspaces-devfile-registry.yaml
dependencies/che-plugin-registry/deploy/openshift/devspaces-plugin-registry.yaml

Fix deployment configurations of devfile and plugin registries to deploy them on OpenShift
Upstream changes: 
- plugin registry: https://github.com/eclipse-che/che-plugin-registry/pull/1809
- devfile registry: https://github.com/eclipse-che/che-devfile-registry/pull/790
To test:
**Plugin Registry**
1.  Login into OS
2.  Execute
```bash
oc new-app -f dependencies/che-plugin-registry/deploy/openshift/devspaces-plugin-registry.yaml \
-p IMAGE="quay.io/devspaces/pluginregistry-rhel8" \
-p IMAGE_TAG="3.9" \
-p PULL_POLICY="Always"
```
3.  You should see:
```
--> Success
Access your application via route 'plugin-registry-vsvydenk-dev.apps.sandbox-stage.gb17.p1.openshiftapps.com' 
Run 'oc status' to view your app.
``` 
4. Got to the route link and add `/v3/plugins` at the end, you should see: …

chore: fix deployments of plugin and devfile regs

---

dependencies/che-plugin-registry/build/dockerfiles/rhel.install.sh

Trying to fix 
CVE-2023-29404 
CVE-2023-24540
CVE-2023-24538
CVE-2023-29405
CVE-2023-29402
All of them are related to go binary that comes with `runc` tool.
After installing runc manually:
```bash
bash-4.4$ runc -v
runc version 1.1.4
spec: 1.0.2-dev
go: go1.19.12
libseccomp: 2.5.2
``` 
before
```bash
bash-4.4$ runc -v
runc version 1.1.4
spec: 1.0.2-dev
go: go1.19.4
libseccomp: 2.5.2
```
https://issues.redhat.com/browse/CRW-4585

chore: install runc manually to update to go1.19.12

---

dependencies/job-config.json

Enabling 3.9 jobs because of 3.9.1.
Leaving everything else enabled because if we disable one branch then someone will need a build of that branch.

enable all jobs

---

dependencies/che-plugin-registry/che-editors.yaml

fix: use https endpoints for the che-code editors
https://issues.redhat.com/browse/CRW-4869
upstream PR - https://github.com/eclipse-che/che-plugin-registry/pull/1810

fix: use https endpoints for the che-code editors

---

dependencies/che-plugin-registry/che-editors.yaml

Cherry-pick of the https://github.com/redhat-developer/devspaces/pull/1022
Related issue https://issues.redhat.com/browse/CRW-4869

fix: use https endpoints for the che-code editors (#1022)

---

dependencies/che-plugin-registry/build/dockerfiles/Dockerfile

Bump registry.redhat.io/rhel8/postgresql-15 image to 1-50.1708914865
https://issues.redhat.com/browse/CRW-5767

fix: bump postgresql-15 base image for plugin reg

---

dependencies/LATEST_IMAGES.sh
product/copyDWOToQuay.sh
product/copyIIBsToQuay.sh
product/util2.groovy

Removing the dash from after the tag in calls to getLatestImageTags.sh because it didn't save us from 3.13-12 and is now breaking things.
https://issues.redhat.com/browse/CRW-5774

Updating calls to getLatestImageTags.sh

---

dependencies/job-config.json

https://issues.redhat.com/browse/CRW-5765
We can't update to 2.11.0 because Cachito is currently incapable of vendoring go 1.22 builds.

Set traefik to v2.10.0

---

dependencies/che-plugin-registry/build/scripts/import_vsix.sh
dependencies/job-config.json

- Upgrade openvsx-server base image to 0.14.5
- Set timeout after publishing each extension to be initialized properly
https://issues.redhat.com/browse/CRW-5751

chore: upgrade local plugin registry to use openvsx-server 0.14.5

---

dependencies/che-plugin-registry/build/scripts/import_vsix.sh
dependencies/che-plugin-registry/openvsx-sync.json

- Add Continue extension into the embedded plugin registry
- Increase timeout for extensions initialization, because 5 seconds is not enough for the activation Continue extension:
before:
after:
https://issues.redhat.com/browse/CRW-6047

Add Continue extension into the embedded plugin registry

---

dependencies/job-config.json

Bump openvsx-server to v0.15.8 version, in this new version spring-security 6.1.9 is used 
https://issues.redhat.com/browse/CRW-6010

chore: bump openvsx-server to v0.15.8

---

dependencies/che-plugin-registry/build/dockerfiles/Dockerfile
dependencies/che-plugin-registry/build/dockerfiles/content_sets_rhel9.repo
dependencies/che-plugin-registry/build/dockerfiles/rhel.Dockerfile
dependencies/che-plugin-registry/build/dockerfiles/rhel.install.sh

Use rhel9-2-els image for the build in Brew
We still have registry.redhat.io/rhel8/postgresql-15 image in the main Dockerfile for the custom plugin registry build
https://issues.redhat.com/browse/CRW-6350

make it possible to use rhel9-2-els image in Brew build

---

dependencies/che-plugin-registry/build/scripts/download_vsix.sh

If vsix extension's vscode engine version is `*`, it should be compatible with all VS Code editor versions
1/ Update openvsx-sync.json file by replacing the content with:
```
[
{
"id": "magicstack.MagicPython",
"version": "1.1.1"
}
]
```
It contains magicstack.MagicPython extension which has [vscode engine version *](https://github.com/MagicStack/MagicPython/blob/master/package.json#L7)
2/ Try to build plugin registry by executing ./build.sh script
3/ Extension should be downloaded and published to the plugin registry
https://issues.redhat.com/browse/CRW-6803

extension's vscode engine version * should be compatible with all VS Code editors

---

dependencies/che-plugin-registry/openvsx-sync.json

Adds [Open Collaboration Tools extension](https://open-vsx.org/extension/typefox/open-collaboration-tools) into the embedded plugin registry
**It could be tested with quay.io/vsvydenk/pluginregistry-rhel8:next image**
https://issues.redhat.com/browse/CRW-6874
Add [Open Collaboration Tools extension](https://open-vsx.org/extension/typefox/open-collaboration-tools) into the Embedded plugin registry

chore: add open-collaboration-tools extension into the embedded plugin reg

---

dependencies/che-plugin-registry/openvsx-sync.json

Backported changes from https://github.com/redhat-developer/devspaces/pull/1092
Adds [Open Collaboration Tools extension](https://open-vsx.org/extension/typefox/open-collaboration-tools) into the embedded plugin registry
**It could be tested with quay.io/vsvydenk/pluginregistry-rhel8:next image**
https://issues.redhat.com/browse/CRW-6874
Add [Open Collaboration Tools extension](https://open-vsx.org/extension/typefox/open-collaboration-tools) into the Embedded plugin registry

chore: add open-collaboration-tools extension into the plugin reg

---

dependencies/che-plugin-registry/build/dockerfiles/Dockerfile
dependencies/che-plugin-registry/build/dockerfiles/application.yaml

- We don't need /v3/plugins/ folder anymore
- Add version of openvsx registry into server config
Dependent PR: https://github.com/eclipse-che/che-operator/pull/1894 
Related to https://github.com/eclipse-che/che/issues/23074

Update openvsx config; remove /v3/plugins from the container

---

dependencies/che-plugin-registry/openvsx-sync.json

Adds `cnshenj.vscode-task-manager` and `Kelvin.vscode-sshfs` into the embedded plugin registry
https://issues.redhat.com/browse/CRW-7481
https://issues.redhat.com/browse/CRW-7482
Add [cnshenj.vscode-task-manager](https://open-vsx.org/extension/cnshenj/vscode-task-manager) and [Kelvin.vscode-sshfs](https://open-vsx.org/extension/Kelvin/vscode-sshfs) extensions into the embedded plugin registry

chore: add vscode-task-manager and vscode-sshfs extensions

---

dependencies/che-plugin-registry/build/dockerfiles/application.yaml

Don't send traces to Zipkin when extensions are installing. The logs in the plugin registry pod are now clearer and more readable:
https://issues.redhat.com/browse/CRW-7257

chore: Skip Zipkin traces for plugin registry
